/**
 * Curriculum configuration for the datas/ → datas.json → MySQL pipeline.
 *
 * One entry per specialty (yo'nalish). `folder` is the directory under datas/ that
 * holds "MODULE n" sub-folders with the Word files; `modules` gives the canonical
 * trilingual titles (taken from the curriculum outline documents in datas/), which
 * override whatever heading the individual dialogue file happens to use.
 *
 *  enabled:false  → parsed into datas.json but NOT seeded unless `node datas.js --all`
 */
module.exports = {
  DATAS_DIR: 'datas',            // relative to the repository root
  OUTPUT_FILE: 'datas/datas.json',

  specialties: [
    {
      code: 'GEN_MED',
      order: 1,
      folder: 'DAVOLASH ISHI',
      name: 'Davolash ishi',
      name_uz: 'Davolash ishi',
      name_ru: 'Лечебное дело',
      name_en: 'General Medicine',
      icon: '🩺',
      student_role: 'doctor',
      setting: 'general medical clinic / hospital admissions unit',
      enabled: true,
      grammar_focus: { 10: 'Mixed Grammar / Revision' },   // other modules state it in the dialogue header
      modules: {
        1:  ['Clinical Consultation & Initial Assessment',                'Klinik konsultatsiya va dastlabki baholash',                     'Клиническая консультация и первичная оценка'],
        2:  ['Acute Chest Pain & Acute Coronary Syndrome',                "O'tkir ko'krak og'rig'i va o'tkir koronar sindrom",              'Острая боль в груди и острый коронарный синдром'],
        3:  ['Acute Asthma Exacerbation',                                 "Bronxial astmaning o'tkir xuruji",                               'Обострение бронхиальной астмы'],
        4:  ['Type 2 Diabetes & Hyperglycemia',                           '2-tur qandli diabet va giperglikemiya',                          'Сахарный диабет 2 типа и гипергликемия'],
        5:  ['Acute Stroke & Time-Critical Assessment',                   "O'tkir insult va vaqt-kritik baholash",                          'Острый инсульт и оценка в условиях дефицита времени'],
        6:  ['Severe Infection & Sepsis Assessment',                      "Og'ir infeksiya va sepsisni baholash",                           'Тяжёлая инфекция и оценка сепсиса'],
        7:  ['Acute Abdominal Pain & Differential Diagnosis',             "O'tkir qorin og'rig'i va differensial tashxis",                  'Острая боль в животе и дифференциальная диагностика'],
        8:  ['Urinary Tract Infection, Pyelonephritis & Kidney Function', "Siydik yo'llari infeksiyasi, piyelonefrit va buyrak faoliyati",  'Инфекция мочевыводящих путей, пиелонефрит и функция почек'],
        9:  ['Anemia, Menorrhagia & Abnormal Bleeding',                   'Anemiya, menorragiya va patologik qon ketish',                   'Анемия, меноррагия и патологические кровотечения'],
        10: ['Full Clinical Consultation & Differential Diagnosis',       "To'liq klinik konsultatsiya va differensial tashxis",            'Полная клиническая консультация и дифференциальная диагностика'],
      },
    },
    {
      code: 'STOM',
      order: 2,
      folder: 'STOMOTOLOGY',
      name: 'Stomatologiya',
      name_uz: 'Stomatologiya',
      name_ru: 'Стоматология',
      name_en: 'Stomatology',
      icon: '🦷',
      student_role: 'dentist',
      setting: 'dental clinic',
      enabled: true,
      modules: {
        1:  ['Dental Pain & Sensitivity',             "Tish og'rig'i va sezuvchanligi",                           'Зубная боль и чувствительность'],
        2:  ['Tooth Extraction',                      'Tishni olib tashlash (ekstraksiya)',                       'Удаление зуба'],
        3:  ['Toothache & Pulpitis',                  "Tish og'rig'i va pulpit",                                  'Зубная боль и пульпит'],
        4:  ['Dental Abscess',                        'Tish abssessi',                                            'Зубной абсцесс'],
        5:  ['Dental Caries',                         'Tish kariesi',                                             'Кариес зубов'],
        6:  ['Gum Problems',                          'Milk kasalliklari',                                        'Заболевания дёсен'],
        7:  ['Impacted Wisdom Tooth',                 "Retensiyalangan (chiqa olmagan) aql tishi",                'Ретинированный зуб мудрости'],
        8:  ['Dental Emergency & Severe Infection',   "Shoshilinch stomatologik holat va og'ir infeksiya",        'Неотложное стоматологическое состояние и тяжёлая инфекция'],
        9:  ['Dental Restoration & Prosthetics',      'Tishlarni tiklash va protezlash',                          'Реставрация и протезирование зубов'],
        10: ['Full Dental Consultation',              "To'liq stomatologik konsultatsiya",                        'Полная стоматологическая консультация'],
      },
      grammar_focus: {
        1:  'Present Simple + Present Perfect + Past Simple + Past Continuous',
        2:  'Present Perfect Continuous + Future Simple',
        3:  'Present Continuous + Past Continuous + Past Perfect Continuous + First Conditional',
        4:  'Present Perfect + Present Perfect Continuous + Passive Voice + Modal Verbs',
        5:  'Modal Verbs + First Conditional + Passive Voice (review)',
        6:  'Present Continuous + be going to + Modal Verbs + Passive Voice + Gerund / Infinitive',
        7:  'Present Perfect Continuous + could + Passive Voice + would rather',
        8:  'Past Perfect + Past Perfect Continuous',
        9:  'Comparatives & Superlatives',
        10: 'Indirect & Polite Questions (revision)',
      },
      // "Virtual Patient vaziyati" / "Talaba nima qiladi?" from Stomatologiya_Virtual_Patient_English_10_Modul.docx
      descriptions_uz: {
        1:  "Bemor sovuq/issiq ta'sirida tishi og'rishidan shikoyat qiladi. Talaba og'riq turi, triggerlari, davomiyligi va kuchini aniqlaydi.",
        2:  'Bemor tish oldirish kerakligi sababli murojaat qiladi. Talaba jarayonni tushuntiradi, xavotirlarini aniqlaydi va savollariga javob beradi.',
        3:  "Bemor kuchli tish og'rig'i bilan keldi. Talaba og'riqning joyi, davomiyligi, kuchi va sabablarini aniqlaydi.",
        4:  "Bemor yuz shishi, kuchli og'riq va isitma bilan keldi. Talaba infeksiya belgilarini aniqlaydi va keyingi davolashni tushuntiradi.",
        5:  'Bemor karies bilan murojaat qildi. Talaba belgilarni muhokama qiladi va davolash variantlarini tushuntiradi.',
        6:  'Bemor milk qonashi va shishidan shikoyat qiladi. Talaba simptomlar, parodont muammolari va davolash haqida suhbatlashadi.',
        7:  "Bemor aql tishi sababli og'riq va shishdan shikoyat qiladi. Talaba simptomlar, avvalgi epizodlar va davolash variantlarini muhokama qiladi.",
        8:  "Bemor kuchli og'riq yoki dental travma bilan keldi. Talaba tezkor savollar berib, shoshilinch vaziyatni baholaydi.",
        9:  "Bemor tishini tiklash uchun implant, crown yoki boshqa protez variantlari haqida maslahat so'raydi. Talaba variantlarning afzallik va kamchiliklarini tushuntiradi.",
        10: "Murakkab realistik bemor bilan to'liq konsultatsiya. Talaba konsultatsiyani boshidan oxirigacha ingliz tilida olib boradi.",
      },
    },
    {
      code: 'PED',
      order: 3,
      folder: 'Pediatrics',
      name: 'Pediatriya ishi',
      name_uz: 'Pediatriya ishi',
      name_ru: 'Педиатрия',
      name_en: 'Pediatrics',
      icon: '👶',
      student_role: 'doctor',
      setting: 'paediatric outpatient clinic / children\'s emergency department (the doctor talks to the parent)',
      enabled: true,
      grammar_focus: {
        1:  'Present Perfect + Present Perfect Continuous + Past Simple vs Present Perfect + used to + Modal Verbs',
        2:  'Present Perfect vs Past Simple + Participles as Adjectives + Relative Clauses',
        3:  'Present Perfect + Present Perfect Continuous + Modal Verbs + First / Zero Conditional + Passive Voice',
        4:  'Articles & Determiners — a/an, the, this/that, these/those, each/every',
        5:  'Modal Verbs for Advice, Obligation & Permission — should, ought to, must, have to, can, may',
        6:  'Comparatives & Superlatives — smaller, taller, more nutritious, the most important',
        7:  'Relative Clauses — who, which, that, whose, where',
        8:  'Adverbs & Adverbial Clauses — rapidly, gradually, carefully; because, although, while',
        9:  'Reported Speech — The mother said that…, The doctor explained that…',
        10: 'Infinitives — to assess, to determine, to monitor, in order to…',
      },
      modules: {
        1:  ['Newborn Care & Common Problems in Newborns',          "Yangi tug'ilgan chaqaloqlar parvarishi va ularda uchraydigan keng tarqalgan muammolar", 'Уход за новорождёнными и распространённые проблемы у новорождённых'],
        2:  ['Fever, Cough & Breathing Problems in Children',       "Bolalarda isitma, yo'tal va nafas olish muammolari",             'Лихорадка, кашель и нарушения дыхания у детей'],
        3:  ['Vomiting, Diarrhea & Dehydration in Children',        'Bolalarda qusish, ich ketishi va suvsizlanish',                  'Рвота, диарея и обезвоживание у детей'],
        4:  ['Childhood Infections & Skin Rashes',                   'Bolalik davridagi infeksiyalar va teri toshmalari',              'Детские инфекции и кожные высыпания'],
        5:  ['Vaccination & Disease Prevention',                     'Emlash va kasalliklarning oldini olish',                         'Вакцинация и профилактика заболеваний'],
        6:  ['Child Growth, Development & Nutrition',                "Bolaning o'sishi, rivojlanishi va ovqatlanishi",                 'Рост, развитие и питание ребёнка'],
        7:  ['Neurological & Developmental Problems in Children',    'Bolalardagi nevrologik va rivojlanish muammolari',               'Неврологические нарушения и проблемы развития у детей'],
        8:  ['Allergies, Asthma & Wheezing in Children',             'Bolalarda allergiya, astma va xirillash',                        'Аллергия, астма и свистящее дыхание у детей'],
        9:  ['Common Pediatric Emergencies',                          "Bolalardagi keng tarqalgan shoshilinch holatlar",                'Распространённые неотложные состояния у детей'],
        10: ['Abdominal Pain, Constipation & Digestive Problems',    "Qorin og'rig'i, qabziyat va ovqat hazm qilish muammolari",       'Боль в животе, запор и нарушения пищеварения'],
      },
    },
    {
      code: 'NURSING',
      order: 4,
      folder: 'NURSERY',
      name: 'Hamshiralik ishi',
      name_uz: 'Hamshiralik ishi',
      name_ru: 'Сестринское дело',
      name_en: 'Nursing',
      icon: '💉',
      student_role: 'nurse',
      setting: 'hospital ward (the nurse talks to the patient, relatives or the doctor)',
      enabled: false,   // content still being finalised — seed with `node datas.js --all` or `--only=NURSING`
      grammar_focus: {
        1: 'Question Forms & Clinical Questions', 2: 'Adverbs of Frequency & Time Expressions', 3: 'Modal Verbs for Rules & Safety',
        4: 'Articles & Determiners', 5: 'Comparatives & Superlatives', 6: 'Cause & Effect: because, due to, therefore, as a result',
        7: 'Imperatives & Infinitives for Instructions', 8: 'Gerund vs Infinitive', 9: 'Reported Speech', 10: 'Future Forms & Plans',
        11: 'Articles & Determiners', 12: 'Question Forms & Indirect Questions', 13: 'Passive Voice', 14: 'Gerund & Infinitive',
        15: 'Countable & Uncountable Nouns + Quantifiers', 16: 'Relative Clauses', 17: 'Main English Tenses + Modifiers', 18: 'Relative Clauses',
      },
      modules: {
        1:  ['Patient Admission & Nursing Assessment',                    'Bemorni qabul qilish va hamshiralik baholashi',                      'Приём пациента и сестринская оценка'],
        2:  ['Vital Signs & Patient Monitoring',                          "Hayotiy ko'rsatkichlar va bemorni kuzatish",                          'Жизненные показатели и наблюдение за пациентом'],
        3:  ['Medication Administration & Safety',                        'Dori vositalarini yuborish va xavfsizlik',                            'Введение лекарств и безопасность'],
        4:  ['Wound Care & Infection Prevention',                         'Yara parvarishi va infeksiyaning oldini olish',                       'Уход за ранами и профилактика инфекций'],
        5:  ['Pain Assessment & Management',                              "Og'riqni baholash va boshqarish",                                     'Оценка и контроль боли'],
        6:  ['Respiratory Problems & Oxygen Therapy',                     'Nafas olish muammolari va kislorod terapiyasi',                       'Дыхательные нарушения и кислородотерапия'],
        7:  ['Emergency Nursing & First Response',                        'Shoshilinch hamshiralik va birinchi yordam',                          'Неотложная помощь и первичная реакция'],
        8:  ['Patient Hygiene, Mobility & Pressure Injury Prevention',    'Bemor gigiyenasi, harakatchanligi va yotoq yaralarining oldini olish', 'Гигиена, мобильность и профилактика пролежней'],
        9:  ['Communication with Patients & Relatives',                   'Bemor va uning yaqinlari bilan muloqot',                              'Общение с пациентами и родственниками'],
        10: ['Discharge Planning & Patient Education',                    "Bemorni chiqarishga tayyorlash va o'qitish",                          'Подготовка к выписке и обучение пациента'],
        11: ['Acute Allergic Reactions & Anaphylaxis',                    "O'tkir allergik reaksiyalar va anafilaksiya",                         'Острые аллергические реакции и анафилаксия'],
        12: ['Chest Pain & Suspected Acute Coronary Syndrome',            "Ko'krak og'rig'i va o'tkir koronar sindromga shubha",                 'Боль в груди и подозрение на острый коронарный синдром'],
        13: ['Stroke Recognition & Initial Management',                   'Insultni aniqlash va dastlabki yordam',                               'Распознавание инсульта и начальная помощь'],
        14: ['Acute Kidney Injury & Fluid Balance',                       "O'tkir buyrak shikastlanishi va suyuqlik muvozanati",                 'Острое повреждение почек и водный баланс'],
        15: ['Electrolyte Imbalances & ECG Changes',                      "Elektrolitlar muvozanati buzilishi va EKG o'zgarishlari",             'Нарушения электролитного баланса и изменения ЭКГ'],
        16: ['Acute Gastrointestinal Bleeding & Initial Assessment',      "O'tkir oshqozon-ichak qon ketishi va dastlabki baholash",             'Острое желудочно-кишечное кровотечение и первичная оценка'],
        17: ['Acute Heart Failure & Fluid Overload',                      "O'tkir yurak yetishmovchiligi va suyuqlik ortiqchaligi",              'Острая сердечная недостаточность и перегрузка жидкостью'],
        18: ['Chronic Disease Management & Lifestyle Advice',             "Surunkali kasalliklarni boshqarish va turmush tarzi bo'yicha maslahatlar", 'Ведение хронических заболеваний и рекомендации по образу жизни'],
      },
    },
    {
      code: 'FIRST_AID',
      order: 5,
      folder: 'First Aid',
      name: 'Tez tibbiy yordam',
      name_uz: 'Tez tibbiy yordam',
      name_ru: 'Скорая медицинская помощь',
      name_en: 'First Aid (Emergency Medicine)',
      icon: '🚑',
      student_role: 'doctor',
      setting: 'emergency department / resuscitation bay',
      enabled: true,
      grammar_focus: {
        1:  'Present Perfect Continuous + Present Perfect + Past Continuous + Conditionals + Modal Verbs',
        2:  'Past Perfect + Past Perfect Continuous',
        3:  'Present Perfect vs Present Perfect Continuous',
        4:  'Passive Voice — Different Tenses',
        5:  'Reported Speech + Reporting Verbs',
        6:  'Gerunds & Infinitives',
        7:  'Participles / Reduced Relative Clauses',
        8:  'Imperatives + Present Perfect + Present Continuous + Modal may + First Conditional',
        9:  'Relative Clauses — Defining & Non-defining',
        10: 'Mixed Conditionals',
      },
      modules: {
        1:  ['Diabetic Emergencies (DKA)',                 'Diabetik shoshilinch holatlar (diabetik ketoatsidoz)',            'Неотложные состояния при диабете (ДКА)'],
        2:  ['Acute Seizures & Status Epilepticus',        "O'tkir tutqanoq xurujlari va epileptik status",                   'Острые судорожные приступы и эпилептический статус'],
        3:  ['Acute Urinary Retention & AKI',              "O'tkir siydik tutilishi va o'tkir buyrak shikastlanishi",         'Острая задержка мочи и острое повреждение почек'],
        4:  ['Thermal Injuries & Burns',                   'Termik shikastlanishlar va kuyishlar',                            'Термические травмы и ожоги'],
        5:  ['Anaphylactic Shock',                         'Anafilaktik shok',                                                'Анафилактический шок'],
        6:  ['Acute Abdomen',                              "O'tkir qorin",                                                    'Острый живот'],
        7:  ['Sepsis & Septic Shock',                      'Sepsis va septik shok',                                           'Сепсис и септический шок'],
        8:  ['Severe Trauma & Hemorrhagic Shock',          "Og'ir travma va gemorragik shok",                                 'Тяжёлая травма и геморрагический шок'],
        9:  ['Syncope & Unexplained Collapse',             "Sinkope (hushdan ketish) va sababi noma'lum kollaps",             'Обморок и коллапс неясной этиологии'],
        10: ['Acute Intoxication & Overdose',              "O'tkir zaharlanish va dori dozasini oshirib yuborish",            'Острое отравление и передозировка'],
      },
    },
  ],
};
