import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const TRANSLATIONS = {
  uz: {
    // App header
    app_title: "Virtual Patient",
    app_subtitle: "English Lab",
    sign_out: "Chiqish",
    navigation: "Menyu",

    // Flat nav keys
    nav_dashboard: "Boshqaruv paneli",
    nav_modules: "Modullar",
    nav_grammar: "Grammatika tekshiruvi",
    nav_forum: "Klinik Forum",
    nav_profile: "Shaxsiy profil",
    nav_groups: "Guruhlar",
    nav_reports: "Hisobotlar",
    nav_overview: "Umumiy ko'rsatkichlar",
    nav_users: "Foydalanuvchilar",
    nav_content: "Kontent menejeri",
    nav_settings: "Sozlamalar",

    // Flat step keys
    step_grammar: "Grammatika",
    step_vocab: "Lug'at",
    step_phrase: "Klinik Iboralar",
    step_gap: "Bo'sh joyni to'ldirish",
    step_quiz: "Test / Quiz",
    step_chat: "Virtual Bemor",
    step_results: "Umumiy Natijalar",
    term_count_suffix: "ta termin",
    phrase_count_suffix: "ta ibora",
    step_badge_1: "1-Bosqich: Grammatika",
    step_badge_2: "2-Bosqich: Lug'at",
    step_badge_3: "3-Bosqich: Iboralar",
    step_badge_4: "4-Bosqich: Mashq",
    step_badge_5: "5-Bosqich: Quiz",
    step_badge_6: "6-Bosqich: Virtual Bemor",
    step_badge_7: "7-Bosqich: Natijalar",

    // Flat chat keys
    chat_header_title: "Virtual Bemor bilan Jonli Muloqot",
    chat_visual_mode: "Vizual Keys",
    chat_transcript_mode: "Suhbat Matni",
    chat_start_voice: "Ovozli Suhbatni Boshlash (STT + TTS)",
    chat_start_text: "Matnli Muloqot",
    chat_test_100: "⚡ Test: 100% bilan yakunlash",
    chat_listening: "Sizni tinglamoqda... Gapiring",
    chat_processing: "Bemor javobi shakllanmoqda...",
    chat_speaking: "Bemor javob bermoqda...",
    chat_ended: "Suhbat yakunlandi",

    // Flat results keys
    results_eval_report: "Rasmiy Klinik Baholash Hisoboti",
    results_passed_desc: "Tabriklaymiz! Siz ushbu modulni muvaffaqiyatli topshirdingiz va klinik mezonlarga to'liq javob berdingiz.",
    results_failed_desc: "Moduldan o'tish uchun kamida 60% talab qilinadi. Iltimos, xatolaringizni ko'rib chiqib, qayta topshiring.",
    results_passed_badge: "Muvaffaqiyatli topshirildi",
    results_failed_badge: "Qayta topshirish kerak",
    results_overall_score: "Umumiy Klinik Ball",
    results_ai_engine: "AI Baholash Tizimi",
    results_competency_matrix: "5 Yo'nalish bo'yicha Klinik Kompetensiya Matritsasi",
    results_max_score: "Maksimal: 10/10 ball",
    results_level_excellent: "A'lo",
    results_level_good: "Yaxshi",
    results_level_needs_work: "Qoniqarsiz",
    results_grammar: "Grammatika",
    results_vocab: "Tibbiy Lug'at",
    results_fluency: "Nutq Ravonligi",
    results_pronunciation: "Talaffuz & Fonetika",
    results_clinical: "Klinik Anamnez",
    results_ai_mentor: "AI Klinik Mentor Xulosasi",
    results_differential_title: "Differensial Xatolar & Tuzatishlar",
    results_all_modules_btn: "Barcha modullarga qaytish",
    results_retry_btn: "Qayta urinish",
    results_next_module_btn: "Keyingi modul: #{id}",

    // Step 1: Grammar
    grammar_title: "Klinik Grammatika & Qoidalar",
    grammar_subtitle: "Bemor bilan to'g'ri va aniq muloqot qilish uchun asosiy grammatik strukturalar",
    grammar_rule: "Grammatik Qoida & Tushuntirish",
    grammar_structure: "Gap Formulasi & Strukturasi",
    grammar_formula_label: "Formula",
    grammar_examples: "Klinik Gap Namunalar",
    grammar_mistakes_title: "Keng Tarqalgan Xatolar va To'g'ri Shakllari",
    grammar_listen: "Talaffuzni tinglash",
    grammar_all_learned: "Grammatikani o'zlashtirdim → Lug'atga o'tish",

    // Step 2: Vocab
    vocab_title: "Klinik Lug'at & Terminologiya",
    vocab_subtitle: "Ushbu mavzudagi asosiy klinik terminlar va talaffuz",
    vocab_definition: "Ta'rif / Ma'nosi",
    vocab_listen: "Talaffuzni tinglash",
    vocab_all_learned: "Lug'atni o'zlashtirdim → Iboralarga o'tish",

    // Step 2: Phrasebook
    phrase_title: "Klinik Iboralar & Muloqot Shablonlari",
    phrase_subtitle: "Bemor bilan anamnez yig'ishda qo'llaniladigan iboralar",
    phrase_doctor: "Shifokor Iborasi",
    phrase_patient_reply: "Bemorning ehtimoliy javobi",
    phrase_hint: "Ma'nosi / Izoh",
    phrase_listen: "Talaffuzni tinglash",
    phrase_all_learned: "Iboralarni o'zlashtirdim → Mashqqa o'tish",

    // Step 3: Gap Filling
    gap_title: "Bo'sh Joylarni To'ldirish Mashqi",
    gap_subtitle: "Klinik iboralarni to'g'ri so'zlar bilan yakunlang",
    gap_check: "Javoblarni tekshirish",
    gap_retry: "Qayta urinish",
    gap_next: "Test / Quiz bosqichiga o'tish",

    // Step 4: Quiz
    quiz_title: "Modul bo'yicha Klinik Test",
    quiz_subtitle: "Bemor bilan muloqotdan oldin bilimlarni tekshiring",
    quiz_check: "Testni yakunlash & Tekshirish",
    quiz_retry: "Qayta topshirish",
    quiz_next: "Virtual Bemor bilan Jonli Muloqotga o'tish",
    back: "Orqaga",

    // Nav & General
    nav: {
      dashboard: "Boshqaruv paneli",
      modules: "Modullar",
      grammar_checker: "Grammatika tekshiruvi",
      forum: "Klinik Forum",
      profile: "Shaxsiy profil",
      groups: "Akademik guruhlar",
      reports: "Hisobotlar",
      overview: "Umumiy ko'rsatkichlar",
      users: "Foydalanuvchilar",
      content: "Kontent menejeri",
      settings: "Sozlamalar",
      sign_out: "Chiqish",
      navigation: "Menyu",
      student_portal: "Talaba Portali",
      teacher_portal: "O'qituvchi Portali",
      admin_portal: "Administrator Portali",
      roles: {
        student: "Talaba",
        teacher: "O'qituvchi",
        admin: "Administrator"
      }
    },
    common: {
      save: "Saqlash",
      cancel: "Bekor qilish",
      delete: "O'chirish",
      edit: "Tahrirlash",
      create: "Yaratish",
      update: "Yangilash",
      close: "Yopish",
      back: "Orqaga",
      next: "Keyingi",
      loading: "Yuklanmoqda...",
      search: "Qidirish...",
      filter: "Filtr",
      actions: "Amallar",
      status: "Holati",
      active: "Faol",
      completed: "Yakunlangan",
      in_progress: "Jarayonda",
      locked: "Qulflangan",
      unlocked: "Ochiq",
      success: "Muvaffaqiyatli",
      error: "Xatolik",
      try_again: "Qayta urinish",
      view_all: "Barchasini ko'rish",
      download_excel: "Excel yuklab olish",
      select: "Tanlang...",
      all: "Barchasi",
      confirm_delete: "Haqiqatan ham ushbu yozuvni o'chirmoqchimisiz?",
      confirm: "Tasdiqlash",
      required_field: "Majburiy maydon",
      all_rights: "Barcha huquqlar himoyalangan",
      or: "yoki",
      yes: "Ha",
      no: "Yo'q",
      score: "Ball",
      attempts: "Urinishlar",
      date: "Sana",
      time: "Vaqt",
      details: "Batafsil",
      view: "Ko'rish",
      language: "Til",
      select_language: "Tilni tanlang",
    },
    auth: {
      login_title: "Tizimga kirish",
      login_subtitle: "Klinik ingliz tili virtual simulyatoriga xush kelibsiz",
      register_title: "Ro'yxatdan o'tish",
      register_subtitle: "Yangi talaba hisobini yaratish",
      email: "Elektron pochta",
      password: "Parol",
      full_name: "To'liq ism-sharifingiz",
      role: "Roli",
      specialty: "Mutaxassislik",
      group: "Akademik guruh",
      sign_in_btn: "Kirish",
      sign_up_btn: "Hisob yaratish",
      no_account: "Hisobingiz yo'qmi?",
      have_account: "Allaqachon hisobingiz bormi?",
      logging_in: "Kirilmoqda...",
      registering: "Yaratilmoqda...",
      invalid_creds: "Elektron pochta yoki parol noto'g'ri",
      welcome_back: "Xush kelibsiz",
      logged_out: "Tizimdan muvaffaqiyatli chiqdingiz",
      select_specialty: "Mutaxassislikni tanlang...",
      select_group: "Guruhni tanlang...",
      enter_email: "email@example.com",
      enter_password: "Parolingizni kiriting",
      enter_full_name: "Jasur Toshmatov",
      demo_hint: "Test akkauntlar:",
    },
    student: {
      dashboard: {
        title: "Talaba Portali",
        greeting_morning: "Xayrli tong",
        greeting_afternoon: "Xayrli kun",
        greeting_evening: "Xayrli kech",
        subtitle: "Yangi modullarni ochish uchun klinik amaliyotni davom ettiring",
        total_modules: "Jami modullar",
        completed_modules: "Yakunlangan",
        average_score: "O'rtacha ball",
        course_progress: "O'quv kursi jarayoni",
        modules_done_of: "{completed} / {total} modul yakunlandi",
        unlock_requirement: "Keyingi modulni ochish uchun kamida 60% kerak",
        recent_activity: "So'nggi faollik",
        no_recent: "Hozircha faollik yo'q. Birinchi moduldan boshlang!",
        view_modules_btn: "Barcha modullarni ko'rish",
        grammar_checker_btn: "Grammatika tekshiruvi",
        start_practice: "Amaliyotni boshlash",
        attempt: "Urinish",
      },
      modules: {
        title: "Klinik O'quv Modullari",
        subtitle: "Interaktiv stomatologik ssenariylar va AI bemor simulyatsiyasi",
        filter_all: "Barcha yo'nalishlar",
        search_placeholder: "Modullarni qidirish...",
        order: "Modul",
        start_btn: "Boshlash",
        continue_btn: "Davom etish",
        review_btn: "Qayta ko'rish",
        completed_badge: "Yakunlangan",
        locked_badge: "Qulflangan",
        best_score: "Eng yaxshi natija",
        unlock_tip: "Ochish uchun avvalgi modulni kamida 60% bilan yakunlang",
      },
      detail: {
        steps: {
          vocab: "Lug'at",
          phrasebook: "Iboralar",
          gap_fill: "Bo'sh joy to'ldirish",
          quiz: "Test sinovi",
          chat: "Virtual Bemor",
          results: "Yakuniy Natijalar",
        },
        step_names: {
          1: "1. Lug'at o'rganish (Vocabulary)",
          2: "2. Klinik iboralar (Phrasebook)",
          3: "3. Bo'sh joylarni to'ldirish (Gap Filling)",
          4: "4. Yakuniy test (Quiz)",
          5: "5. Virtual Bemor bilan muloqot",
          6: "6. Modul natijalari & Sertifikat",
        },
        listen_audio: "Talaffuzni tinglash",
        meaning: "Ma'nosi / Tarjimasi",
        definition: "Klinik ta'rif",
        example: "Misol gap",
        category: "Kategoriya",
        hint: "Klinik izoh",
        gap_fill_desc: "Klinik iboralardagi tushirib qoldirilgan tibbiy so'zlarni to'g'ri tanlang",
        check_answers: "Javoblarni tekshirish",
        try_again_gap: "Qaytadan urinish",
        gap_passed: "Ajoyib natija! Barcha bo'sh joylar to'g'ri to'ldirildi.",
        gap_failed: "Ba'zi javoblarda xatolik bor. Qayta tekshirib ko'ring.",
        quiz_desc: "Modul mavzusi bo'yicha test savollariga to'g'ri javob bering",
        quiz_question_of: "{current} / {total}-savol",
        submit_quiz: "Testni yakunlash",
        quiz_result: "Test natijasi",
        quiz_passed: "Test muvaffaqiyatli topshirildi!",
        quiz_failed: "Testdan o'tish uchun kamida 60% to'plang",
        start_chat_btn: "Bemor bilan suhbatni boshlash",
        chat_subtitle: "AI bemor bilan audio yoki matnli professional tibbiy muloqot o'tkazing",
        hold_to_speak: "Gapirish uchun bosing va ushlab turing",
        listening: "Tinglanmoqda...",
        send_message: "Yuborish",
        type_message_placeholder: "Ingliz tilida klinik savolingizni yozing...",
        end_consultation: "Konsultatsiyani yakunlash va AI baholashni olish",
        patient_info: "Bemor haqida",
        complaint: "Asosiy shikoyat",
        symptoms: "Simptomlar",
        clinical_guide: "Klinik yo'riqnoma",
        ai_evaluation_title: "AI Ko'p Omilli Baholash",
        total_score: "Umumiy ball",
        metrics: {
          grammar: "Grammatika",
          vocabulary: "Tibbiy lug'at",
          fluency: "Muloqot ravonligi",
          pronunciation: "Talaffuz",
          clinical: "Klinik to'g'rilik",
        },
        strengths: "Kuchli tomonlar",
        weaknesses: "Kamchiliklar va e'tibor berish kerak bo'lgan jihatlar",
        corrections: "Grammatik va uslubiy tuzatishlar",
        original_sentence: "Talaba aytgan jumla",
        suggested_sentence: "Tavsiya etilgan to'g'ri variant",
        explanation: "Izoh / Qoida",
        next_module: "Keyingi modulga o'tish",
        retry_simulation: "Simulyatsiyani qayta topshirish",
        module_congratulations: "Tabriklaymiz! Siz ushbu modulni muvaffaqiyatli yakunladingiz!",
        certificate_ready: "Modul sertifikati tayyor",
      },
      grammar: {
        title: "Klinik Grammatika Tekshiruvchisi",
        subtitle: "Tibbiy ingliz tilidagi jumlalaringizni AI orqali professional darajada tahlil qiling",
        input_label: "Tahlil qilinadigan tibbiy matnni kiriting",
        placeholder: "Masalan: The patient have severe toothache and I prescribe him antibiotics...",
        check_btn: "Matnni tahlil qilish",
        checking: "AI tahlil qilmoqda...",
        clear_btn: "Tozalash",
        sample_btn: "Namuna matn",
        result_title: "Tahlil natijalari",
        accuracy_score: "Grammatik aniqlik",
        corrected_version: "Klinik to'g'irlangan variant",
        detailed_fixes: "Batafsil xatolar tahlili",
        vocab_suggestions: "Tavsiya etiladigan tibbiy atamalar",
        tone_analysis: "Muloqot ohangi va klinik etika",
      },
      forum: {
        title: "Klinik Muloqot Forumi",
        subtitle: "Talabalar va o'qituvchilar o'rtasida murakkab klinik keyslar muhokamasi",
        new_post_btn: "Yangi mavzu ochish",
        search_placeholder: "Forumdan qidirish...",
        categories: "Mavzu toifalari",
        all_topics: "Barcha mavzular",
        replies_count: "ta javob",
        views: "ko'rildi",
        post_by: "Muallif",
        reply_placeholder: "Klinik fikringizni yozing...",
        send_reply_btn: "Javob yuborish",
        topic_title: "Mavzu sarlavhasi",
        topic_content: "Keys / savol matni",
        create_topic_btn: "Mavzuni e'lon qilish",
      },
      profile: {
        title: "Shaxsiy Profil & Statistika",
        subtitle: "O'zlashtirish ko'rsatkichlari, modullar tarixi va radar tahlili",
        personal_info: "Shaxsiy ma'lumotlar",
        overall_stats: "Umumiy ko'rsatkichlar",
        radar_title: "5 Omilli Ko'nikmalar Radari",
        history_title: "Modullarni topshirish tarixi",
        module_name: "Modul nomi",
        best_score: "Eng yaxshi ball",
        attempts_count: "Urinishlar",
        last_attempt: "Oxirgi urinish",
        status: "Holati",
      }
    },
    teacher: {
      dashboard: {
        title: "O'qituvchi Boshqaruv Paneli",
        subtitle: "Biriktirilgan guruhlar va talabalar natijalarini real vaqtda kuzating",
        assigned_groups: "Biriktirilgan guruhlar",
        total_students: "Jami talabalar",
        group_avg_score: "Guruh o'rtacha bali",
        completed_sessions: "Yakunlangan simulyatsiyalar",
        recent_student_activity: "Talabalarning so'nggi natijalari",
        quick_reports_btn: "Hisobotlarga o'tish",
      },
      groups: {
        title: "Akademik Guruhlar",
        subtitle: "Sizga biriktirilgan talabalar ro'yxati va individual monitoring",
        select_group: "Guruhni tanlang",
        students_in_group: "Guruhdagi talabalar",
        student_name: "Talaba F.I.Sh.",
        modules_completed: "O'zlashtirilgan modullar",
        average_score: "O'rtacha ball",
        last_active: "So'nggi faollik",
        view_student_details: "Batafsil tahlil",
      },
      reports: {
        title: "Klinik Natijalar Hisoboti",
        subtitle: "Guruhlar kesimida kengaytirilgan tahlil va Excel eksport",
        export_btn: "Excel hisobotni yuklab olish",
        filter_group: "Guruh bo'yicha",
        filter_module: "Modul bo'yicha",
        all_modules: "Barcha modullar",
        common_mistakes_title: "Guruhda eng ko'p uchragan grammatik va klinik xatolar",
        error_frequency: "Uchrashlar soni",
        error_description: "Xato turi va tushuntirish",
        students_table: "Talabalar natijalari jadvali",
      }
    },
    admin: {
      overview: {
        title: "Tizim Umumiy Ko'rsatkichlari",
        subtitle: "Foydalanuvchilar, modullar va simulyatsiyalar global statistikasi",
        total_students: "Talabalar soni",
        total_teachers: "O'qituvchilar soni",
        total_admins: "Adminlar soni",
        total_modules: "O'quv modullari",
        total_simulations: "Yakunlangan simulyatsiyalar",
        global_avg: "Global o'rtacha ball",
        specialties_analytics: "Mutaxassisliklar bo'yicha tahlil",
        groups_count: "Guruhlar soni",
      },
      users: {
        title: "Foydalanuvchilar Boshqaruvi",
        subtitle: "Talabalar, o'qituvchilar va administratorlar hisoblarini boshqarish",
        add_user_btn: "Yangi foydalanuvchi",
        edit_user: "Foydalanuvchini tahrirlash",
        filter_role: "Rol bo'yicha filtr",
        user_name: "F.I.Sh.",
        email: "Email",
        role: "Roli",
        specialty: "Mutaxassislik",
        group: "Guruh",
        created_at: "Qo'shilgan sana",
        password_hint: "Parolni o'zgartirmaslik uchun bo'sh qoldiring",
      },
      groups_page: {
        title: "Guruhlar & Yo'nalishlar",
        subtitle: "Mutaxassisliklar, akademik guruhlar va o'qituvchilarni biriktirish",
        add_specialty_btn: "Yangi Mutaxassislik",
        add_group_btn: "Yangi Guruh",
        specialties_title: "Mutaxassisliklar (Kafedralar)",
        groups_title: "Akademik Guruhlar",
        assigned_teachers: "Biriktirilgan o'qituvchilar",
        assign_teacher_btn: "O'qituvchi biriktirish",
        specialty_name: "Mutaxassislik nomi",
        group_name: "Guruh nomi",
        student_count: "Talabalar soni",
      },
      content: {
        title: "Kontent & Ma'lumotlar Menejeri",
        subtitle: "Modullar, lug'at, iboralar va test savollarini oson boshqaring",
        tabs: {
          vocabulary: "Lug'at (Vocabulary)",
          phrasebook: "Iboralar (Phrasebook)",
          quizzes: "Testlar (Quizzes)",
          scenarios: "Modullar (Scenarios)",
        },
        select_module: "Modulni tanlang",
        add_item_btn: "Yangi qo'shish",
        search_content: "Kontentdan qidirish...",
        vocab_fields: {
          word: "Inglizcha so'z (Word)",
          trans_uz: "O'zbekcha tarjima",
          trans_ru: "Ruscha tarjima",
          trans_en: "Inglizcha izoh/sinonim",
          def_uz: "O'zbekcha klinik ta'rif",
          def_ru: "Ruscha klinik ta'rif",
          def_en: "Inglizcha klinik ta'rif",
          example: "Klinik misol gap (Example)",
        },
        phrase_fields: {
          category: "Kategoriya / Klinik Bosqich",
          phrase: "Inglizcha muloqot iborasi (Phrase)",
          hint_uz: "O'zbekcha izoh / tarjima",
          hint_ru: "Ruscha izoh / tarjima",
          hint_en: "Inglizcha izoh",
          step_order: "Tartib raqami",
        },
        quiz_fields: {
          question: "Savol matni (Question)",
          option_a: "A varianti",
          option_b: "B varianti",
          option_c: "C varianti",
          option_d: "D varianti",
          correct_option: "To'g'ri javob",
        },
        module_fields: {
          order_index: "Tartib raqami",
          specialty: "Mutaxassislik",
          title: "Modul nomi",
          description: "Qisqacha tavsifi",
          patient_context: "AI Standart Bemor Konteksti (Inglizcha)",
          final_challenge_context: "Final Challenge Murakkab Bemor Konteksti",
        }
      }
    }
  },

  ru: {
    // App header
    app_title: "Virtual Patient",
    app_subtitle: "English Lab",
    sign_out: "Выйти",
    navigation: "Навигация",

    // Flat nav keys
    nav_dashboard: "Панель управления",
    nav_modules: "Модули",
    nav_grammar: "Проверка грамматики",
    nav_forum: "Клинический форум",
    nav_profile: "Мой профиль",
    nav_groups: "Группы",
    nav_reports: "Отчеты",
    nav_overview: "Обзор системы",
    nav_users: "Пользователи",
    nav_content: "Менеджер контента",
    nav_settings: "Настройки",

    // Flat step keys
    step_grammar: "Грамматика",
    step_vocab: "Словарь",
    step_phrase: "Клинические фразы",
    step_gap: "Заполнение пропусков",
    step_quiz: "Тест / Квиз",
    step_chat: "Виртуальный пациент",
    step_results: "Итоговые результаты",
    term_count_suffix: "терминов",
    phrase_count_suffix: "фраз",
    step_badge_1: "1-й этап: Грамматика",
    step_badge_2: "2-й этап: Словарь",
    step_badge_3: "3-й этап: Фразы",
    step_badge_4: "4-й этап: Практика",
    step_badge_5: "5-й этап: Квиз",
    step_badge_6: "6-й этап: Виртуальный пациент",
    step_badge_7: "7-й этап: Результаты",

    // Flat chat keys
    chat_header_title: "Живой Диалог с Виртуальным Пациентом",
    chat_visual_mode: "Визуальный Кейс",
    chat_transcript_mode: "Транскрипт Диалога",
    chat_start_voice: "Начать Голосовой Диалог (STT + TTS)",
    chat_start_text: "Текстовый Диалог",
    chat_test_100: "⚡ Тест: Завершить на 100%",
    chat_listening: "Слушаю вас... Говорите",
    chat_processing: "Пациент формирует ответ...",
    chat_speaking: "Пациент отвечает...",
    chat_ended: "Диалог завершен",

    // Flat results keys
    results_eval_report: "Официальный Отчет об Оценке",
    results_passed_desc: "Поздравляем! Вы успешно прошли этот модуль и выполнили все клинические требования.",
    results_failed_desc: "Для прохождения модуля требуется минимум 60%. Пожалуйста, просмотрите ошибки и попробуйте снова.",
    results_passed_badge: "Успешно пройдено",
    results_failed_badge: "Требуется пересдача",
    results_overall_score: "Общий Клинический Балл",
    results_ai_engine: "Система Оценки AI",
    results_competency_matrix: "Матрица Клинических Компетенций по 5 Направлениям",
    results_max_score: "Максимально: 10/10 баллов",
    results_level_excellent: "Отлично",
    results_level_good: "Хорошо",
    results_level_needs_work: "Удовлетворительно",
    results_grammar: "Грамматика",
    results_vocab: "Медицинский Словарь",
    results_fluency: "Беглость Речи",
    results_pronunciation: "Произношение & Фонетика",
    results_clinical: "Клинический Анамнез",
    results_ai_mentor: "Заключение AI Клинического Ментора",
    results_differential_title: "Дифференциальные Ошибки & Исправления",
    results_all_modules_btn: "Вернуться ко всем модулям",
    results_retry_btn: "Попробовать снова",
    results_next_module_btn: "Следующий модуль: #{id}",

    // Step 1: Grammar
    grammar_title: "Клиническая Грамматика & Правила",
    grammar_subtitle: "Ключевые грамматические структуры для точного и уверенного общения с пациентом",
    grammar_rule: "Грамматическое Правило & Контекст",
    grammar_structure: "Формула и Структура Предложения",
    grammar_formula_label: "Формула",
    grammar_examples: "Клинические Примеры Предложений",
    grammar_mistakes_title: "Типичные Ошибки и Правильные Формы",
    grammar_listen: "Слушать произношение",
    grammar_all_learned: "Грамматика усвоена → Перейти к словарю",

    // Step 2: Vocab
    vocab_title: "Клинический Словарь & Терминология",
    vocab_subtitle: "Ключевые клинические термины и произношение",
    vocab_definition: "Определение / Значение",
    vocab_listen: "Слушать произношение",
    vocab_all_learned: "Словарь усвоен → Перейти к фразам",

    // Step 2: Phrasebook
    phrase_title: "Клинические Фразы & Шаблоны Диалога",
    phrase_subtitle: "Фразы для сбора анамнеза у пациента",
    phrase_doctor: "Фраза Врача",
    phrase_patient_reply: "Возможный ответ пациента",
    phrase_hint: "Значение / Перевод",
    phrase_listen: "Слушать фразу",
    phrase_all_learned: "Фразы усвоены → Перейти к упражнениям",

    // Step 3: Gap Filling
    gap_title: "Упражнение: Заполнение Пропусков",
    gap_subtitle: "Дополните клинические фразы правильными словами",
    gap_check: "Проверить ответы",
    gap_retry: "Попробовать снова",
    gap_next: "Перейти к Тесту / Квизу",

    // Step 4: Quiz
    quiz_title: "Клинический Тест по Модулю",
    quiz_subtitle: "Проверьте знания перед симуляцией с пациентом",
    quiz_check: "Завершить тест & Проверить",
    quiz_retry: "Попробовать снова",
    quiz_next: "Перейти к Виртуальному Пациенту",
    back: "Назад",

    // Nav & General
    nav: {
      dashboard: "Панель управления",
      modules: "Модули",
      grammar_checker: "Проверка грамматики",
      forum: "Клинический форум",
      profile: "Мой профиль",
      groups: "Академические группы",
      reports: "Отчеты",
      overview: "Обзор системы",
      users: "Пользователи",
      content: "Менеджер контента",
      settings: "Настройки",
      sign_out: "Выйти",
      navigation: "Навигация",
      student_portal: "Портал студента",
      teacher_portal: "Портал преподавателя",
      admin_portal: "Портал администратора",
      roles: {
        student: "Студент",
        teacher: "Преподаватель",
        admin: "Администратор"
      }
    },
    common: {
      save: "Сохранить",
      cancel: "Отмена",
      delete: "Удалить",
      edit: "Редактировать",
      create: "Создать",
      update: "Обновить",
      close: "Закрыть",
      back: "Назад",
      next: "Далее",
      loading: "Загрузка...",
      search: "Поиск...",
      filter: "Фильтр",
      actions: "Действия",
      status: "Статус",
      active: "Активен",
      completed: "Завершено",
      in_progress: "В процессе",
      locked: "Заблокировано",
      unlocked: "Доступно",
      success: "Успешно",
      error: "Ошибка",
      try_again: "Попробовать снова",
      view_all: "Посмотреть все",
      download_excel: "Скачать Excel",
      select: "Выберите...",
      all: "Все",
      confirm_delete: "Вы действительно хотите удалить эту запись?",
      confirm: "Подтвердить",
      required_field: "Обязательное поле",
      all_rights: "Все права защищены",
      or: "или",
      yes: "Да",
      no: "Нет",
      score: "Балл",
      attempts: "Попытки",
      date: "Дата",
      time: "Время",
      details: "Подробнее",
      view: "Просмотр",
      language: "Язык",
      select_language: "Выберите язык",
    },
    auth: {
      login_title: "Вход в систему",
      login_subtitle: "Добро пожаловать в виртуальный симулятор клинического английского",
      register_title: "Регистрация",
      register_subtitle: "Создание учетной записи студента",
      email: "Электронная почта",
      password: "Пароль",
      full_name: "Ф.И.О.",
      role: "Роль",
      specialty: "Специальность",
      group: "Академическая группа",
      sign_in_btn: "Войти",
      sign_up_btn: "Создать аккаунт",
      no_account: "Нет учетной записи?",
      have_account: "Уже есть аккаунт?",
      logging_in: "Вход...",
      registering: "Создание...",
      invalid_creds: "Неверный адрес электронной почты или пароль",
      welcome_back: "С возвращением",
      logged_out: "Вы успешно вышли из системы",
      select_specialty: "Выберите специальность...",
      select_group: "Выберите группу...",
      enter_email: "email@example.com",
      enter_password: "Ваш пароль",
      enter_full_name: "Иван Иванов",
      demo_hint: "Тестовые аккаунты:",
    },
    student: {
      dashboard: {
        title: "Портал студента",
        greeting_morning: "Доброе утро",
        greeting_afternoon: "Добрый день",
        greeting_evening: "Добрый вечер",
        subtitle: "Продолжайте клиническую практику, чтобы открывать новые модули",
        total_modules: "Всего модулей",
        completed_modules: "Завершено",
        average_score: "Средний балл",
        course_progress: "Прогресс обучения",
        modules_done_of: "Завершено {completed} из {total} модулей",
        unlock_requirement: "Для разблокировки следующего модуля требуется от 60%",
        recent_activity: "Недавняя активность",
        no_recent: "Пока нет активности. Начните с первого модуля!",
        view_modules_btn: "Все учебные модули",
        grammar_checker_btn: "Проверка грамматики",
        start_practice: "Начать практику",
        attempt: "Попытка",
      },
      modules: {
        title: "Клинические учебные модули",
        subtitle: "Интерактивные стоматологические сценарии и симуляция AI пациентов",
        filter_all: "Все специальности",
        search_placeholder: "Поиск модулей...",
        order: "Модуль",
        start_btn: "Начать",
        continue_btn: "Продолжить",
        review_btn: "Повторить",
        completed_badge: "Пройден",
        locked_badge: "Закрыт",
        best_score: "Лучший балл",
        unlock_tip: "Завершите предыдущий модуль минимум на 60%, чтобы открыть",
      },
      detail: {
        steps: {
          vocab: "Словарь",
          phrasebook: "Фразы",
          gap_fill: "Вставка слов",
          quiz: "Тестирование",
          chat: "Виртуальный пациент",
          results: "Итоги",
        },
        step_names: {
          1: "1. Изучение терминов (Vocabulary)",
          2: "2. Клинические фразы (Phrasebook)",
          3: "3. Заполнение пропусков (Gap Filling)",
          4: "4. Финальный тест (Quiz)",
          5: "5. Диалог с виртуальным пациентом",
          6: "6. Результаты модуля и сертификат",
        },
        listen_audio: "Прослушать произношение",
        meaning: "Перевод / Значение",
        definition: "Клиническое определение",
        example: "Пример предложения",
        category: "Категория",
        hint: "Клиническая подсказка",
        gap_fill_desc: "Выберите пропущенные медицинские термины в клинических фразах",
        check_answers: "Проверить ответы",
        try_again_gap: "Попробовать снова",
        gap_passed: "Отличный результат! Все пропуски заполнены верно.",
        gap_failed: "Есть ошибки в ответах. Попробуйте еще раз.",
        quiz_desc: "Ответьте на вопросы по теме модуля",
        quiz_question_of: "Вопрос {current} из {total}",
        submit_quiz: "Завершить тест",
        quiz_result: "Результат теста",
        quiz_passed: "Тест успешно сдан!",
        quiz_failed: "Для прохождения теста необходимо набрать минимум 60%",
        start_chat_btn: "Начать консультацию с пациентом",
        chat_subtitle: "Проведите профессиональный медицинский опрос на английском языке (голосом или текстом)",
        hold_to_speak: "Нажмите и удерживайте для записи речи",
        listening: "Слушаю...",
        send_message: "Отправить",
        type_message_placeholder: "Введите ваш клинический вопрос на английском...",
        end_consultation: "Завершить прием и получить оценку AI",
        patient_info: "Информация о пациенте",
        complaint: "Главная жалоба",
        symptoms: "Симптомы",
        clinical_guide: "Клинический протокол",
        ai_evaluation_title: "Многофакторная оценка AI",
        total_score: "Общий балл",
        metrics: {
          grammar: "Грамматика",
          vocabulary: "Медицинская лексика",
          fluency: "Беглость речи",
          pronunciation: "Произношение",
          clinical: "Клиническая точность",
        },
        strengths: "Сильные стороны",
        weaknesses: "Замечания и зоны для улучшения",
        corrections: "Грамматические и стилистические исправления",
        original_sentence: "Ваша фраза",
        suggested_sentence: "Рекомендуемый вариант",
        explanation: "Пояснение / Правило",
        next_module: "Перейти к следующему модулю",
        retry_simulation: "Повторить симуляцию",
        module_congratulations: "Поздравляем! Вы успешно завершили этот модуль!",
        certificate_ready: "Сертификат модуля готов",
      },
      grammar: {
        title: "Клинический грамматический анализатор",
        subtitle: "Проверьте свои медицинские фразы на английском языке с помощью ИИ",
        input_label: "Введите клинический текст для анализа",
        placeholder: "Например: The patient have severe toothache and I prescribe him antibiotics...",
        check_btn: "Анализировать текст",
        checking: "ИИ проводит анализ...",
        clear_btn: "Очистить",
        sample_btn: "Пример текста",
        result_title: "Результаты анализа",
        accuracy_score: "Грамматическая точность",
        corrected_version: "Исправленная версия",
        detailed_fixes: "Подробный разбор ошибок",
        vocab_suggestions: "Рекомендуемая профессиональная лексика",
        tone_analysis: "Тон общения и медицинская этика",
      },
      forum: {
        title: "Клинический форум",
        subtitle: "Обсуждение сложных клинических случаев между студентами и преподавателями",
        new_post_btn: "Создать тему",
        search_placeholder: "Поиск по форуму...",
        categories: "Категории",
        all_topics: "Все темы",
        replies_count: "ответов",
        views: "просмотров",
        post_by: "Автор",
        reply_placeholder: "Напишите ваш клинический ответ...",
        send_reply_btn: "Отправить ответ",
        topic_title: "Заголовок темы",
        topic_content: "Текст клинического случая",
        create_topic_btn: "Опубликовать тему",
      },
      profile: {
        title: "Профиль и статистика",
        subtitle: "Показатели успеваемости, история модулей и радар навыков",
        personal_info: "Личная информация",
        overall_stats: "Общие показатели",
        radar_title: "5-факторный радар клинических навыков",
        history_title: "История прохождения модулей",
        module_name: "Название модуля",
        best_score: "Лучший балл",
        attempts_count: "Попытки",
        last_attempt: "Последняя попытка",
        status: "Статус",
      }
    },
    teacher: {
      dashboard: {
        title: "Панель преподавателя",
        subtitle: "Мониторинг успеваемости студентов и закрепленных групп в реальном времени",
        assigned_groups: "Закрепленные группы",
        total_students: "Всего студентов",
        group_avg_score: "Средний балл групп",
        completed_sessions: "Завершенных диалогов",
        recent_student_activity: "Последние результаты студентов",
        quick_reports_btn: "Перейти к отчетам",
      },
      groups: {
        title: "Академические группы",
        subtitle: "Список студентов ваших групп и индивидуальный прогресс",
        select_group: "Выберите группу",
        students_in_group: "Студенты группы",
        student_name: "Ф.И.О. студента",
        modules_completed: "Пройдено модулей",
        average_score: "Средний балл",
        last_active: "Последняя активность",
        view_student_details: "Подробный анализ",
      },
      reports: {
        title: "Отчеты по клиническим модулям",
        subtitle: "Глубокая аналитика успеваемости и экспорт в Excel",
        export_btn: "Экспорт в Excel",
        filter_group: "По группе",
        filter_module: "По модулю",
        all_modules: "Все модули",
        common_mistakes_title: "Наиболее частые грамматические и клинические ошибки",
        error_frequency: "Частота ошибок",
        error_description: "Тип ошибки и рекомендации",
        students_table: "Таблица результатов студентов",
      }
    },
    admin: {
      overview: {
        title: "Обзор системы",
        subtitle: "Глобальная статистика платформы, пользователей и симуляций",
        total_students: "Студентов",
        total_teachers: "Преподавателей",
        total_admins: "Администраторов",
        total_modules: "Учебных модулей",
        total_simulations: "Завершенных сессий",
        global_avg: "Глобальный средний балл",
        specialties_analytics: "Аналитика по специальностям",
        groups_count: "Количество групп",
      },
      users: {
        title: "Управление пользователями",
        subtitle: "Создание, редактирование и назначение ролей пользователей",
        add_user_btn: "Добавить пользователя",
        edit_user: "Редактировать пользователя",
        filter_role: "Фильтр по роли",
        user_name: "Ф.И.О.",
        email: "Email",
        role: "Роль",
        specialty: "Специальность",
        group: "Группа",
        created_at: "Дата создания",
        password_hint: "Оставьте пустым, чтобы не менять пароль",
      },
      groups_page: {
        title: "Группы и специальности",
        subtitle: "Управление кафедрами, академическими группами и преподавателями",
        add_specialty_btn: "Новая специальность",
        add_group_btn: "Новая группа",
        specialties_title: "Специальности (Кафедры)",
        groups_title: "Академические группы",
        assigned_teachers: "Закрепленные преподаватели",
        assign_teacher_btn: "Назначить преподавателя",
        specialty_name: "Название специальности",
        group_name: "Название группы",
        student_count: "Количество студентов",
      },
      content: {
        title: "Менеджер контента и данных",
        subtitle: "Управление модулями, словарем, фразами и тестовыми заданиями",
        tabs: {
          vocabulary: "Lug'at (Vocabulary)",
          phrasebook: "Iboralar (Phrasebook)",
          quizzes: "Testlar (Quizzes)",
          scenarios: "Modullar (Scenarios)",
        },
        select_module: "Выберите модуль",
        add_item_btn: "Добавить элемент",
        search_content: "Поиск по контенту...",
        vocab_fields: {
          word: "Английское слово (Word)",
          trans_uz: "Перевод на узбекский",
          trans_ru: "Перевод на русский",
          trans_en: "Определение / Синоним на английском",
          def_uz: "Определение на узбекском",
          def_ru: "Определение на русском",
          def_en: "Определение на английском",
          example: "Клинический пример (Example)",
        },
        phrase_fields: {
          category: "Категория / Клинический этап",
          phrase: "Клиническая фраза на английском (Phrase)",
          hint_uz: "Подсказка на узбекском",
          hint_ru: "Подсказка на русском",
          hint_en: "Пояснение на английском",
          step_order: "Порядковый номер",
        },
        quiz_fields: {
          question: "Текст вопроса на английском (Question)",
          option_a: "Вариант A",
          option_b: "Вариант B",
          option_c: "Вариант C",
          option_d: "Вариант D",
          correct_option: "Правильный ответ",
        },
        module_fields: {
          order_index: "Порядковый номер",
          specialty: "Специальность",
          title: "Название модуля",
          description: "Краткое описание",
          patient_context: "Стандартный контекст AI пациента (на английском)",
          final_challenge_context: "Контекст усложненного Final Challenge",
        }
      }
    }
  },

  en: {
    // App header
    app_title: "Virtual Patient",
    app_subtitle: "English Lab",
    sign_out: "Sign out",
    navigation: "Navigation",

    // Flat nav keys
    nav_dashboard: "Dashboard",
    nav_modules: "Modules",
    nav_grammar: "Grammar Checker",
    nav_forum: "Clinical Forum",
    nav_profile: "My Profile",
    nav_groups: "Groups",
    nav_reports: "Reports",
    nav_overview: "System Overview",
    nav_users: "Users",
    nav_content: "Content Manager",
    nav_settings: "Settings",

    // Flat step keys
    step_grammar: "Grammar",
    step_vocab: "Vocabulary",
    step_phrase: "Clinical Phrases",
    step_gap: "Gap Practice",
    step_quiz: "Quiz / Test",
    step_chat: "Virtual Patient",
    step_results: "Overall Results",
    term_count_suffix: "terms",
    phrase_count_suffix: "phrases",
    step_badge_1: "Step 1: Grammar",
    step_badge_2: "Step 2: Vocabulary",
    step_badge_3: "Step 3: Phrases",
    step_badge_4: "Step 4: Practice",
    step_badge_5: "Step 5: Quiz",
    step_badge_6: "Step 6: Virtual Patient",
    step_badge_7: "Step 7: Results",

    // Flat chat keys
    chat_header_title: "Live Virtual Patient Dialogue",
    chat_visual_mode: "Visual Case",
    chat_transcript_mode: "Conversation Transcript",
    chat_start_voice: "Start Voice Dialogue (STT + TTS)",
    chat_start_text: "Text Dialogue",
    chat_test_100: "⚡ Test: Pass 100%",
    chat_listening: "Listening to you... Speak now",
    chat_processing: "Patient formulating response...",
    chat_speaking: "Patient speaking...",
    chat_ended: "Dialogue ended",

    // Flat results keys
    results_eval_report: "Official Clinical Evaluation Report",
    results_passed_desc: "Congratulations! You have successfully passed this module and satisfied all clinical criteria.",
    results_failed_desc: "A minimum of 60% is required to pass this module. Please review your errors and retry.",
    results_passed_badge: "Passed Successfully",
    results_failed_badge: "Retry Required",
    results_overall_score: "Overall Clinical Score",
    results_ai_engine: "AI Evaluation System",
    results_competency_matrix: "5-Metric Clinical Competency Matrix",
    results_max_score: "Maximum: 10/10 points",
    results_level_excellent: "Excellent",
    results_level_good: "Good",
    results_level_needs_work: "Needs Work",
    results_grammar: "Grammar Accuracy",
    results_vocab: "Medical Vocabulary",
    results_fluency: "Speech Fluency",
    results_pronunciation: "Pronunciation & Phonetics",
    results_clinical: "Clinical History Taking",
    results_ai_mentor: "AI Clinical Mentor Assessment",
    results_differential_title: "Differential Errors & Corrections",
    results_all_modules_btn: "Back to all modules",
    results_retry_btn: "Retry Module",
    results_next_module_btn: "Next Module: #{id}",

    // Step 1: Grammar
    grammar_title: "Clinical Grammar & Language Structures",
    grammar_subtitle: "Essential grammatical structures for precise and confident clinical communication",
    grammar_rule: "Grammar Rule & Context",
    grammar_structure: "Sentence Formula & Structure",
    grammar_formula_label: "Formula",
    grammar_examples: "Clinical Sentence Examples",
    grammar_mistakes_title: "Common Pitfalls vs. Correct Medical Usage",
    grammar_listen: "Listen pronunciation",
    grammar_all_learned: "Grammar Mastered → Proceed to Vocabulary",

    // Step 2: Vocab
    vocab_title: "Clinical Vocabulary & Terminology",
    vocab_subtitle: "Core clinical terms and pronunciation for this module",
    vocab_definition: "Definition / Meaning",
    vocab_listen: "Listen pronunciation",
    vocab_all_learned: "Vocabulary Mastered → Continue to Phrases",

    // Step 2: Phrasebook
    phrase_title: "Clinical Phrases & Dialogue Templates",
    phrase_subtitle: "Essential phrases for clinical history taking with patients",
    phrase_doctor: "Doctor Phrase",
    phrase_patient_reply: "Likely Patient Response",
    phrase_hint: "Clinical Context",
    phrase_listen: "Listen to phrase",
    phrase_all_learned: "Phrases Mastered → Proceed to Practice",

    // Step 3: Gap Filling
    gap_title: "Gap Filling Clinical Practice",
    gap_subtitle: "Complete medical phrases with the correct clinical terms",
    gap_check: "Check Answers",
    gap_retry: "Retry Exercise",
    gap_next: "Proceed to Clinical Quiz",

    // Step 4: Quiz
    quiz_title: "Module Clinical Knowledge Quiz",
    quiz_subtitle: "Verify clinical understanding before patient simulation",
    quiz_check: "Submit & Evaluate Quiz",
    quiz_retry: "Retry Quiz",
    quiz_next: "Proceed to Live Patient Dialogue",
    back: "Back",

    // Nav & General
    nav: {
      dashboard: "Dashboard",
      modules: "Modules",
      grammar_checker: "Grammar Checker",
      forum: "Clinical Forum",
      profile: "My Profile",
      groups: "Academic Groups",
      reports: "Reports",
      overview: "System Overview",
      users: "Users",
      content: "Content Manager",
      settings: "Settings",
      sign_out: "Sign out",
      navigation: "Navigation",
      student_portal: "Student Portal",
      teacher_portal: "Teacher Portal",
      admin_portal: "Admin Portal",
      roles: {
        student: "Student",
        teacher: "Teacher",
        admin: "Admin"
      }
    },
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      create: "Create",
      update: "Update",
      close: "Close",
      back: "Back",
      next: "Next",
      loading: "Loading...",
      search: "Search...",
      filter: "Filter",
      actions: "Actions",
      status: "Status",
      active: "Active",
      completed: "Completed",
      in_progress: "In Progress",
      locked: "Locked",
      unlocked: "Unlocked",
      success: "Success",
      error: "Error",
      try_again: "Try Again",
      view_all: "View All",
      download_excel: "Download Excel",
      select: "Select...",
      all: "All",
      confirm_delete: "Are you sure you want to delete this record?",
      confirm: "Confirm",
      required_field: "Required field",
      all_rights: "All rights reserved",
      or: "or",
      yes: "Yes",
      no: "No",
      score: "Score",
      attempts: "Attempts",
      date: "Date",
      time: "Time",
      details: "Details",
      view: "View",
      language: "Language",
      select_language: "Select language",
    },
    auth: {
      login_title: "Sign in to account",
      login_subtitle: "Welcome to Virtual Patient English Communication Simulator",
      register_title: "Create an Account",
      register_subtitle: "Register as a student",
      email: "Email address",
      password: "Password",
      full_name: "Full Name",
      role: "Role",
      specialty: "Specialty",
      group: "Academic Group",
      sign_in_btn: "Sign In",
      sign_up_btn: "Create Account",
      no_account: "Don't have an account?",
      have_account: "Already have an account?",
      logging_in: "Signing in...",
      registering: "Creating...",
      invalid_creds: "Invalid email or password",
      welcome_back: "Welcome back",
      logged_out: "Signed out successfully",
      select_specialty: "Select specialty...",
      select_group: "Select group...",
      enter_email: "email@example.com",
      enter_password: "Enter your password",
      enter_full_name: "John Doe",
      demo_hint: "Demo accounts:",
    },
    student: {
      dashboard: {
        title: "Student Portal",
        greeting_morning: "Good morning",
        greeting_afternoon: "Good afternoon",
        greeting_evening: "Good evening",
        subtitle: "Practice clinical conversations to master medical English and unlock modules",
        total_modules: "Total Modules",
        completed_modules: "Completed",
        average_score: "Average Score",
        course_progress: "Course Progress",
        modules_done_of: "{completed} of {total} modules completed",
        unlock_requirement: "60% or higher required on previous module to unlock next",
        recent_activity: "Recent Activity",
        no_recent: "No activity yet. Start with Module 1!",
        view_modules_btn: "View All Modules",
        grammar_checker_btn: "Grammar Checker",
        start_practice: "Start Practice",
        attempt: "Attempt",
      },
      modules: {
        title: "Clinical English Modules",
        subtitle: "Interactive dental cases, speech training, and AI patient simulations",
        filter_all: "All Specialties",
        search_placeholder: "Search modules...",
        order: "Module",
        start_btn: "Start",
        continue_btn: "Continue",
        review_btn: "Review",
        completed_badge: "Completed",
        locked_badge: "Locked",
        best_score: "Best Score",
        unlock_tip: "Pass previous module with at least 60% score to unlock",
      },
      detail: {
        steps: {
          vocab: "Vocabulary",
          phrasebook: "Phrasebook",
          gap_fill: "Gap Filling",
          quiz: "Quiz",
          chat: "Virtual Patient",
          results: "Results",
        },
        step_names: {
          1: "1. Medical Vocabulary",
          2: "2. Clinical Phrasebook",
          3: "3. Gap Filling Exercise",
          4: "4. Knowledge Quiz",
          5: "5. Virtual Patient Consultation",
          6: "6. Evaluation & Certificate",
        },
        listen_audio: "Listen to pronunciation",
        meaning: "Meaning / Translation",
        definition: "Clinical Definition",
        example: "Example Sentence",
        category: "Category",
        hint: "Clinical Hint",
        gap_fill_desc: "Fill in the missing medical terminology into doctor-patient phrases",
        check_answers: "Check Answers",
        try_again_gap: "Try Again",
        gap_passed: "Well done! All gaps filled accurately.",
        gap_failed: "Some answers are incorrect. Please review and try again.",
        quiz_desc: "Test your comprehension with multiple-choice questions",
        quiz_question_of: "Question {current} of {total}",
        submit_quiz: "Submit Quiz",
        quiz_result: "Quiz Results",
        quiz_passed: "Quiz successfully passed!",
        quiz_failed: "Score at least 60% to pass the quiz",
        start_chat_btn: "Start Consultation with Patient",
        chat_subtitle: "Conduct an authentic dental consultation in English using voice or text",
        hold_to_speak: "Hold to speak",
        listening: "Listening...",
        send_message: "Send",
        type_message_placeholder: "Type your clinical response in English...",
        end_consultation: "End Consultation & Get AI Evaluation",
        patient_info: "Patient Overview",
        complaint: "Chief Complaint",
        symptoms: "Symptoms",
        clinical_guide: "Clinical Guideline",
        ai_evaluation_title: "AI Multi-Factor Assessment",
        total_score: "Overall Score",
        metrics: {
          grammar: "Grammar",
          vocabulary: "Medical Vocabulary",
          fluency: "Fluency",
          pronunciation: "Pronunciation",
          clinical: "Clinical Accuracy",
        },
        strengths: "Clinical Strengths",
        weaknesses: "Areas for Improvement",
        corrections: "Grammar & Phrasing Corrections",
        original_sentence: "Your Utterance",
        suggested_sentence: "Recommended Correction",
        explanation: "Rule & Clinical Context",
        next_module: "Next Module",
        retry_simulation: "Retry Simulation",
        module_congratulations: "Congratulations! You have completed this module!",
        certificate_ready: "Module Certificate Ready",
      },
      grammar: {
        title: "Clinical Grammar Checker",
        subtitle: "Analyze and refine your medical English clinical notes and consultations",
        input_label: "Enter clinical text for analysis",
        placeholder: "Example: The patient have severe toothache and I prescribe him antibiotics...",
        check_btn: "Analyze Clinical Text",
        checking: "AI analyzing text...",
        clear_btn: "Clear",
        sample_btn: "Sample Text",
        result_title: "Analysis Results",
        accuracy_score: "Grammar Accuracy",
        corrected_version: "Polished Clinical Text",
        detailed_fixes: "Detailed Error Corrections",
        vocab_suggestions: "Professional Medical Terms",
        tone_analysis: "Doctor-Patient Tone & Ethics",
      },
      forum: {
        title: "Clinical Discussion Forum",
        subtitle: "Discuss difficult patient cases and collaborate with peers and faculty",
        new_post_btn: "New Discussion",
        search_placeholder: "Search discussions...",
        categories: "Categories",
        all_topics: "All Topics",
        replies_count: "replies",
        views: "views",
        post_by: "Author",
        reply_placeholder: "Write your clinical opinion...",
        send_reply_btn: "Post Reply",
        topic_title: "Topic Title",
        topic_content: "Case details / Clinical questions",
        create_topic_btn: "Publish Topic",
      },
      profile: {
        title: "Profile & Skill Analytics",
        subtitle: "Track your learning progress, radar breakdown, and simulation logs",
        personal_info: "Personal Details",
        overall_stats: "Performance Overview",
        radar_title: "5-Factor Clinical English Radar",
        history_title: "Module Completion History",
        module_name: "Module Name",
        best_score: "Best Score",
        attempts_count: "Attempts",
        last_attempt: "Last Attempt",
        status: "Status",
      }
    },
    teacher: {
      dashboard: {
        title: "Teacher Dashboard",
        subtitle: "Real-time overview of student performance across assigned academic groups",
        assigned_groups: "Assigned Groups",
        total_students: "Total Students",
        group_avg_score: "Group Average",
        completed_sessions: "Completed Simulations",
        recent_student_activity: "Recent Student Activity",
        quick_reports_btn: "Go to Reports",
      },
      groups: {
        title: "Academic Groups",
        subtitle: "Manage your assigned students and monitor their individual mastery",
        select_group: "Select Group",
        students_in_group: "Students in Group",
        student_name: "Student Name",
        modules_completed: "Modules Passed",
        average_score: "Average Score",
        last_active: "Last Active",
        view_student_details: "Detailed Analytics",
      },
      reports: {
        title: "Clinical Performance Reports",
        subtitle: "Comprehensive analytics by group and module with Excel export",
        export_btn: "Export Excel Report",
        filter_group: "By Group",
        filter_module: "By Module",
        all_modules: "All Modules",
        common_mistakes_title: "Most Common Grammar & Clinical Pitfalls in Group",
        error_frequency: "Frequency",
        error_description: "Error Pattern & Guidance",
        students_table: "Student Results Table",
      }
    },
    admin: {
      overview: {
        title: "System Overview",
        subtitle: "Global statistics for students, faculty, simulations, and modules",
        total_students: "Total Students",
        total_teachers: "Total Teachers",
        total_admins: "Total Admins",
        total_modules: "Clinical Modules",
        total_simulations: "Completed Sessions",
        global_avg: "Global Average Score",
        specialties_analytics: "Analytics by Medical Specialty",
        groups_count: "Total Groups",
      },
      users: {
        title: "User Management",
        subtitle: "Manage student, teacher, and administrator accounts and access",
        add_user_btn: "Add User",
        edit_user: "Edit User",
        filter_role: "Filter by Role",
        user_name: "Full Name",
        email: "Email",
        role: "Role",
        specialty: "Specialty",
        group: "Group",
        created_at: "Created Date",
        password_hint: "Leave empty to keep existing password",
      },
      groups_page: {
        title: "Groups & Specialties",
        subtitle: "Manage academic departments, student cohorts, and teacher assignments",
        add_specialty_btn: "New Specialty",
        add_group_btn: "New Group",
        specialties_title: "Specialties & Departments",
        groups_title: "Academic Groups",
        assigned_teachers: "Assigned Teachers",
        assign_teacher_btn: "Assign Teacher",
        specialty_name: "Specialty Name",
        group_name: "Group Name",
        student_count: "Student Count",
      },
      content: {
        title: "Content & Data Manager",
        subtitle: "Manage dental modules, vocabulary terms, phrasebooks, and quiz questions",
        tabs: {
          vocabulary: "Vocabulary",
          phrasebook: "Phrasebook",
          quizzes: "Quizzes",
          scenarios: "Module Scenarios",
        },
        select_module: "Select Module",
        add_item_btn: "Add New Item",
        search_content: "Search content...",
        vocab_fields: {
          word: "English Term (Word)",
          trans_uz: "Uzbek Translation",
          trans_ru: "Russian Translation",
          trans_en: "English Synonym / Meaning",
          def_uz: "Uzbek Clinical Definition",
          def_ru: "Russian Clinical Definition",
          def_en: "English Clinical Definition",
          example: "Clinical Example Sentence",
        },
        phrase_fields: {
          category: "Category / Clinical Stage",
          phrase: "English Clinical Phrase",
          hint_uz: "Uzbek Translation / Hint",
          hint_ru: "Russian Translation / Hint",
          hint_en: "English Explanation",
          step_order: "Step Order",
        },
        quiz_fields: {
          question: "Question in English",
          option_a: "Option A",
          option_b: "Option B",
          option_c: "Option C",
          option_d: "Option D",
          correct_option: "Correct Option",
        },
        module_fields: {
          order_index: "Order Index",
          specialty: "Specialty",
          title: "Module Title",
          description: "Brief Description",
          patient_context: "AI Patient Persona & Context (English)",
          final_challenge_context: "Final Challenge Advanced Context",
        }
      }
    }
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem('vpe_lang');
    return saved && ['uz', 'ru', 'en'].includes(saved) ? saved : 'uz';
  });

  const setLanguage = (lang) => {
    if (['uz', 'ru', 'en'].includes(lang)) {
      setLanguageState(lang);
      localStorage.setItem('vpe_lang', lang);
    }
  };

  const changeLanguage = setLanguage;

  // Helper to safely get nested or flat key from TRANSLATIONS e.g. "student.dashboard.title" or "nav_dashboard"
  const t = (path, params = {}) => {
    if (!path) return '';

    // Direct check in current language dict
    const currentDict = TRANSLATIONS[language] || TRANSLATIONS.uz;
    if (currentDict[path] !== undefined && typeof currentDict[path] === 'string') {
      let val = currentDict[path];
      for (const [pk, pv] of Object.entries(params)) {
        val = val.replace(new RegExp(`\\{${pk}\\}`, 'g'), pv);
      }
      return val;
    }

    // Nested path traversal
    const keys = path.split('.');
    let val = currentDict;
    let found = true;
    for (const k of keys) {
      if (val && val[k] !== undefined) {
        val = val[k];
      } else {
        found = false;
        break;
      }
    }

    if (!found || val === undefined) {
      // Fallback to uz then en
      const fallbackDict = TRANSLATIONS.uz;
      let fbVal = fallbackDict;
      let fbFound = true;
      for (const fk of keys) {
        if (fbVal && fbVal[fk] !== undefined) {
          fbVal = fbVal[fk];
        } else {
          fbFound = false;
          break;
        }
      }
      val = fbFound ? fbVal : (currentDict[path] || path);
    }

    if (typeof val === 'string') {
      let result = val;
      for (const [pk, pv] of Object.entries(params)) {
        result = result.replace(new RegExp(`\\{${pk}\\}`, 'g'), pv);
      }
      return result;
    }
    return val !== undefined ? val : path;
  };

  // Helper to dynamically get translation of a content item (vocabulary, phrase, module)
  const getLocalized = (item, field = 'translation') => {
    if (!item) return '';

    if (field === 'translation') {
      if (language === 'uz') {
        return item.translation_uz || item.translation || item.translation_ru || item.translation_en || item.word || '';
      } else if (language === 'ru') {
        return item.translation_ru || item.translation || item.translation_uz || item.translation_en || item.word || '';
      } else {
        return item.translation_en || item.definition_en || item.definition || item.translation || item.word || '';
      }
    }

    if (field === 'definition') {
      if (language === 'uz') {
        return item.definition_uz || item.definition || item.definition_ru || item.definition_en || '';
      } else if (language === 'ru') {
        return item.definition_ru || item.definition || item.definition_uz || item.definition_en || '';
      } else {
        return item.definition_en || item.definition || item.definition_uz || '';
      }
    }

    if (field === 'hint' || field === 'phrase_hint') {
      if (language === 'uz') {
        return item.hint_uz || item.translation_uz || item.hint_ru || item.hint_en || '';
      } else if (language === 'ru') {
        return item.hint_ru || item.translation_ru || item.hint_uz || item.hint_en || '';
      } else {
        return item.hint_en || item.translation_en || item.hint_uz || '';
      }
    }

    if (field === 'description') {
      if (language === 'uz') {
        return item.description_uz || item.description || item.description_ru || item.description_en || '';
      } else if (language === 'ru') {
        return item.description_ru || item.description || item.description_uz || item.description_en || '';
      } else {
        return item.description_en || item.description || '';
      }
    }

    return item[field] || '';
  };

  const getTranslation = getLocalized;

  return (
    <LanguageContext.Provider value={{
      language,
      lang: language,
      setLanguage,
      changeLanguage,
      t,
      getLocalized,
      getTranslation,
      getTranslated: getLocalized
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
