/**
 * Grammar knowledge base — concise, trilingual reference explanations for the
 * grammar topics that occur in the curriculum. Used ONLY as a fallback when a
 * Word file explains a rule in one language (usually Uzbek) but not the others,
 * or gives no formula. Nothing here is module-specific; it is standard B1–B2
 * grammar wording in a clinical-English framing.
 */

const KB = {
  present_simple: {
    name: 'Present Simple',
    match: /present simple|hozirgi oddiy|настоящее простое/i,
    formula: 'Subject + V1 (he/she/it + V-s) | Do/Does + subject + V1?',
    signal: 'usually, often, every day, sometimes, never',
    en: 'Present Simple describes habits, routines, general facts and permanent states. In the clinic it is used for typical symptoms ("The pain usually starts at night"), regular medication and general medical facts.',
    uz: "Present Simple odatiy, takrorlanuvchi harakatlar, umumiy faktlar va doimiy holatlarni bildiradi. Klinikada odatdagi simptomlar (\"The pain usually starts at night\"), muntazam dori qabuli va umumiy tibbiy faktlar uchun ishlatiladi.",
    ru: 'Present Simple описывает привычные, регулярные действия, общие факты и постоянные состояния. В клинике используется для типичных симптомов («The pain usually starts at night»), регулярного приёма лекарств и общих медицинских фактов.',
  },
  present_continuous: {
    name: 'Present Continuous',
    match: /present continuous|present progressive|hozirgi davomli|настоящее длительное/i,
    formula: 'am / is / are + V-ing',
    signal: 'now, at the moment, currently, today, these days',
    en: 'Present Continuous describes what is happening now or a temporary, changing situation: "His condition is getting worse", "I am going to examine you now". It is also used for the immediate plan of the clinician.',
    uz: "Present Continuous ayni paytda bo'layotgan yoki vaqtinchalik, o'zgarayotgan holatni bildiradi: \"His condition is getting worse\", \"I am going to examine you now\". Shifokorning hozirgi rejasini aytishda ham ishlatiladi.",
    ru: 'Present Continuous описывает действие в момент речи или временную, меняющуюся ситуацию: «His condition is getting worse», «I am going to examine you now». Также используется для ближайших действий врача.',
  },
  present_perfect: {
    name: 'Present Perfect',
    match: /present perfect(?! continuous| progressive)|hozirgi tugallangan|настоящее совершённое|настоящее совершенное/i,
    formula: 'have / has + V3 | Have/Has + subject + V3?',
    signal: 'already, yet, just, ever, never, since, for, recently, so far',
    en: 'Present Perfect links a past event to the present: an experience, a recent event or a result that matters now. In history taking it asks about symptoms and events up to now: "Have you had any fever?", "I have vomited three times".',
    uz: "Present Perfect o'tmishdagi voqeani hozirgi holat bilan bog'laydi: tajriba, yaqinda bo'lgan voqea yoki hozir muhim bo'lgan natija. Anamnez yig'ishda hozirgacha bo'lgan simptomlar so'raladi: \"Have you had any fever?\", \"I have vomited three times\".",
    ru: 'Present Perfect связывает прошлое событие с настоящим: опыт, недавнее событие или результат, важный сейчас. При сборе анамнеза так спрашивают о симптомах вплоть до настоящего момента: «Have you had any fever?», «I have vomited three times».',
  },
  present_perfect_continuous: {
    name: 'Present Perfect Continuous',
    match: /present perfect continuous|present perfect progressive|have been \+ v-ing|has been \+ v-ing/i,
    formula: 'have / has + been + V-ing',
    signal: 'since, for, how long, lately, recently, all day',
    en: 'Present Perfect Continuous describes an action that started in the past and is still continuing (or has just stopped and its effect is visible). It is the key tense for symptom duration: "How long have you been feeling unwell?" — "I have been coughing for five days".',
    uz: "Present Perfect Continuous o'tmishda boshlanib hozirgacha davom etayotgan (yoki hozirgina to'xtagan va ta'siri sezilayotgan) harakatni bildiradi. Simptom davomiyligi uchun asosiy zamon: \"How long have you been feeling unwell?\" — \"I have been coughing for five days\".",
    ru: 'Present Perfect Continuous описывает действие, которое началось в прошлом и всё ещё продолжается (или только что закончилось и результат заметен). Ключевое время для длительности симптомов: «How long have you been feeling unwell?» — «I have been coughing for five days».',
  },
  past_simple: {
    name: 'Past Simple',
    match: /past simple|o'tgan oddiy|прошедшее простое|simple past/i,
    formula: 'Subject + V2 (V-ed) | Did + subject + V1? | was / were',
    signal: 'yesterday, last night, two days ago, in 2020, when',
    en: 'Past Simple describes completed events at a definite time in the past: "The pain started yesterday", "When did you take the last dose?". Use it whenever the time is finished or stated.',
    uz: "Past Simple o'tmishda aniq vaqtda tugagan voqealarni bildiradi: \"The pain started yesterday\", \"When did you take the last dose?\". Vaqt tugagan yoki aniq ko'rsatilgan bo'lsa shu zamon ishlatiladi.",
    ru: 'Past Simple описывает завершённые события в определённое время в прошлом: «The pain started yesterday», «When did you take the last dose?». Используется, когда время закончилось или названо.',
  },
  past_continuous: {
    name: 'Past Continuous',
    match: /past continuous|past progressive|o'tgan davomli|прошедшее длительное/i,
    formula: 'was / were + V-ing',
    signal: 'while, when, at that moment, all morning',
    en: 'Past Continuous describes an action in progress at a moment in the past, often interrupted by a Past Simple event: "I was carrying boxes when I suddenly felt chest pain". It gives the background of the onset.',
    uz: "Past Continuous o'tmishdagi ma'lum paytda davom etayotgan harakatni bildiradi, ko'pincha Past Simple dagi voqea uni to'xtatadi: \"I was carrying boxes when I suddenly felt chest pain\". Simptom boshlangan vaziyatni tasvirlaydi.",
    ru: 'Past Continuous описывает действие в процессе в определённый момент прошлого, часто прерванное событием в Past Simple: «I was carrying boxes when I suddenly felt chest pain». Показывает обстоятельства начала симптома.',
  },
  past_perfect: {
    name: 'Past Perfect',
    match: /past perfect(?! continuous| progressive)|o'tgan tugallangan|прошедшее совершённое|had \+ v3/i,
    formula: 'had + V3',
    signal: 'before, after, by the time, already, until, when',
    en: 'Past Perfect shows that one past action happened before another past action: "I had eaten a large meal before the pain started". It orders events in the clinical timeline.',
    uz: "Past Perfect o'tmishdagi bir harakat boshqa o'tmishdagi harakatdan oldin bo'lganini ko'rsatadi: \"I had eaten a large meal before the pain started\". Klinik voqealar ketma-ketligini aniqlashda ishlatiladi.",
    ru: 'Past Perfect показывает, что одно действие в прошлом произошло раньше другого: «I had eaten a large meal before the pain started». Упорядочивает события в клинической хронологии.',
  },
  past_perfect_continuous: {
    name: 'Past Perfect Continuous',
    match: /past perfect continuous|past perfect progressive|had been \+ v-ing/i,
    formula: 'had + been + V-ing',
    signal: 'for, since, before, until',
    en: 'Past Perfect Continuous describes an action that had been going on for some time before another past event: "I had been feeling dizzy for ten minutes before I collapsed". It stresses duration before the key event.',
    uz: "Past Perfect Continuous o'tmishdagi boshqa voqeadan oldin bir muddat davom etgan harakatni bildiradi: \"I had been feeling dizzy for ten minutes before I collapsed\". Asosiy voqeadan oldingi davomiylikni ta'kidlaydi.",
    ru: 'Past Perfect Continuous описывает действие, которое длилось некоторое время до другого события в прошлом: «I had been feeling dizzy for ten minutes before I collapsed». Подчёркивает длительность до ключевого события.',
  },
  future_simple: {
    name: 'Future Simple (will)',
    match: /future simple|\bwill\b(?! be \+ v3)|kelasi oddiy|будущее простое/i,
    formula: 'will + V1 | will not (won\'t) + V1',
    signal: 'tomorrow, next week, soon, in a few minutes, I think',
    en: '"Will" expresses decisions made now, promises, predictions and reassurance: "I will give you something for the pain", "The swelling will go down in a few days".',
    uz: "\"Will\" hozir qabul qilingan qaror, va'da, bashorat va bemorni tinchlantirishni ifodalaydi: \"I will give you something for the pain\", \"The swelling will go down in a few days\".",
    ru: '«Will» выражает решение, принятое в момент речи, обещание, прогноз и успокоение пациента: «I will give you something for the pain», «The swelling will go down in a few days».',
  },
  be_going_to: {
    name: 'be going to',
    match: /going to|kelajakdagi reja|собираться/i,
    formula: 'am / is / are + going to + V1',
    signal: 'now, next, first, then',
    en: '"Be going to" describes a plan or intention and something about to happen: "I am going to examine your abdomen now", "We are going to run some tests". Clinicians use it to announce each step of the examination.',
    uz: "\"Be going to\" reja, niyat yoki hozir sodir bo'ladigan harakatni bildiradi: \"I am going to examine your abdomen now\", \"We are going to run some tests\". Shifokor tekshiruvning har bir bosqichini shu qolip bilan e'lon qiladi.",
    ru: '«Be going to» выражает план, намерение или то, что вот-вот произойдёт: «I am going to examine your abdomen now», «We are going to run some tests». Врач так объявляет каждый шаг осмотра.',
  },
  future_perfect: {
    name: 'Future Perfect / Future Continuous',
    match: /future perfect|future continuous|will have \+ v3|will be \+ v-ing/i,
    formula: 'will have + V3 | will be + V-ing',
    signal: 'by tomorrow, by the end of, at this time tomorrow',
    en: 'Future Perfect ("will have + V3") says an action will be completed before a future moment; Future Continuous ("will be + V-ing") describes an action in progress at a future time: "By tomorrow you will have received the results", "The nurse will be monitoring you overnight".',
    uz: "Future Perfect (\"will have + V3\") harakat kelajakdagi ma'lum paytgacha tugashini, Future Continuous (\"will be + V-ing\") esa kelajakda davom etayotgan harakatni bildiradi: \"By tomorrow you will have received the results\", \"The nurse will be monitoring you overnight\".",
    ru: 'Future Perfect («will have + V3») означает, что действие завершится к определённому моменту в будущем; Future Continuous («will be + V-ing») — действие будет длиться в будущем: «By tomorrow you will have received the results», «The nurse will be monitoring you overnight».',
  },
  used_to: {
    name: 'used to',
    match: /used to/i,
    formula: 'used to + V1 | didn\'t use to + V1',
    signal: 'before, in the past, previously',
    en: '"Used to" describes past habits or states that are no longer true: "I used to smoke twenty cigarettes a day". It is useful for past lifestyle and previous medication.',
    uz: "\"Used to\" hozir mavjud bo'lmagan o'tmishdagi odat yoki holatni bildiradi: \"I used to smoke twenty cigarettes a day\". O'tmishdagi turmush tarzi va avvalgi dorilar haqida so'rashda qulay.",
    ru: '«Used to» описывает прошлые привычки или состояния, которых больше нет: «I used to smoke twenty cigarettes a day». Удобно для расспроса о прежнем образе жизни и предыдущих лекарствах.',
  },
  zero_conditional: {
    name: 'Zero Conditional',
    match: /zero conditional|0 conditional|nol tur shart|нулевой тип/i,
    formula: 'If + Present Simple, Present Simple',
    signal: 'if, when, whenever',
    en: 'Zero Conditional states general truths and medical facts: "If children lose too much fluid, they become dehydrated". Both parts use the Present Simple.',
    uz: "Zero Conditional umumiy haqiqat va tibbiy faktlarni bildiradi: \"If children lose too much fluid, they become dehydrated\". Ikkala qismda ham Present Simple ishlatiladi.",
    ru: 'Zero Conditional выражает общие истины и медицинские факты: «If children lose too much fluid, they become dehydrated». В обеих частях используется Present Simple.',
  },
  first_conditional: {
    name: 'First Conditional',
    match: /first conditional|1st conditional|conditional (type )?1|type 1|birinchi tur shart|первый тип|real (future )?condition/i,
    formula: 'If + Present Simple, will / can / should + V1',
    signal: 'if, unless, as soon as, when',
    en: 'First Conditional describes a real, possible future situation and its result. Clinicians use it for warnings, plans and safety-netting: "If the pain gets worse, you should come back immediately". Do not use "will" after "if".',
    uz: "First Conditional real, ehtimoliy kelajakdagi vaziyat va uning natijasini bildiradi. Shifokor ogohlantirish, reja va xavfsizlik ko'rsatmalari uchun ishlatadi: \"If the pain gets worse, you should come back immediately\". \"If\" dan keyin \"will\" ishlatilmaydi.",
    ru: 'First Conditional описывает реальную, возможную ситуацию в будущем и её результат. Врач использует его для предупреждений, планов и рекомендаций по безопасности: «If the pain gets worse, you should come back immediately». После «if» «will» не ставится.',
  },
  second_conditional: {
    name: 'Second Conditional',
    match: /second conditional|2nd conditional|conditional (type )?2|type 2|ikkinchi tur shart|второй тип|hypothetical present/i,
    formula: 'If + Past Simple, would / could / might + V1',
    signal: 'if, if I were you',
    en: 'Second Conditional describes an unreal or unlikely present/future situation: "If we knew exactly what he had taken, we could assess the risk better". "If I were you, I would…" gives tactful advice.',
    uz: "Second Conditional hozirgi yoki kelajakdagi noreal, ehtimoli kam vaziyatni bildiradi: \"If we knew exactly what he had taken, we could assess the risk better\". \"If I were you, I would…\" — muloyim maslahat berish qolipi.",
    ru: 'Second Conditional описывает нереальную или маловероятную ситуацию в настоящем/будущем: «If we knew exactly what he had taken, we could assess the risk better». «If I were you, I would…» — тактичный совет.',
  },
  third_conditional: {
    name: 'Third Conditional',
    match: /third conditional|3rd conditional|conditional (type )?3|type 3|uchinchi tur shart|третий тип/i,
    formula: 'If + Past Perfect, would / might / could + have + V3',
    signal: 'if, had … would have',
    en: 'Third Conditional talks about an unreal past situation and its past result — often to explain what could have been avoided: "If he had taken a smaller dose, he might not have become so drowsy".',
    uz: "Third Conditional o'tmishdagi noreal vaziyat va uning o'tmishdagi natijasini bildiradi — ko'pincha nimadan qochish mumkin edi, deb tushuntirishda: \"If he had taken a smaller dose, he might not have become so drowsy\".",
    ru: 'Third Conditional говорит о нереальной ситуации в прошлом и её прошлом результате — часто чтобы объяснить, чего можно было избежать: «If he had taken a smaller dose, he might not have become so drowsy».',
  },
  mixed_conditional: {
    name: 'Mixed Conditional',
    match: /mixed conditional|aralash shart|смешанн/i,
    formula: 'If + Past Perfect, would / might + V1 (now)',
    signal: 'if … had …, now',
    en: 'Mixed Conditional combines a past condition with a present result: "If he had taken a smaller amount, he might not be this drowsy now". It links a past decision to the current clinical picture.',
    uz: "Mixed Conditional o'tmishdagi shartni hozirgi natija bilan bog'laydi: \"If he had taken a smaller amount, he might not be this drowsy now\". O'tmishdagi qaror bilan hozirgi klinik holat orasidagi aloqani ko'rsatadi.",
    ru: 'Mixed Conditional соединяет условие в прошлом с результатом в настоящем: «If he had taken a smaller amount, he might not be this drowsy now». Связывает прошлое решение с текущей клинической картиной.',
  },
  passive: {
    name: 'Passive Voice',
    match: /passive|majhul|страдательн|be \+ v3|been \+ v3/i,
    formula: 'be (am/is/are/was/were/will be/has been) + V3 | modal + be + V3',
    signal: 'by, will be, has been, needs to be',
    en: 'Passive Voice is used when the action or the patient matters more than who performs it — typical for tests, procedures and treatment plans: "Blood samples will be taken", "You will be referred to a specialist", "The wound has been cleaned".',
    uz: "Passive Voice harakatni kim bajarayotganidan ko'ra harakatning o'zi yoki bemor muhim bo'lganda ishlatiladi — tahlillar, muolajalar va davolash rejasi uchun odatiy: \"Blood samples will be taken\", \"You will be referred to a specialist\", \"The wound has been cleaned\".",
    ru: 'Passive Voice используется, когда важнее само действие или пациент, а не исполнитель — типично для анализов, процедур и плана лечения: «Blood samples will be taken», «You will be referred to a specialist», «The wound has been cleaned».',
  },
  modals: {
    name: 'Modal Verbs',
    match: /modal|modallik|модальн/i,
    formula: 'modal (can / could / may / might / must / should / have to) + V1',
    signal: 'possibility, advice, necessity, permission',
    en: 'Modal verbs add the speaker\'s attitude: possibility (may, might, could), ability/permission (can, could), advice (should, ought to), obligation (must, have to) and prohibition (mustn\'t). The main verb after a modal is always the base form.',
    uz: "Modal fe'llar gapga munosabat qo'shadi: ehtimollik (may, might, could), imkoniyat/ruxsat (can, could), maslahat (should, ought to), majburiyat (must, have to) va taqiq (mustn't). Modaldan keyin fe'l doim asosiy shaklda (V1) keladi.",
    ru: 'Модальные глаголы передают отношение говорящего: возможность (may, might, could), способность/разрешение (can, could), совет (should, ought to), обязанность (must, have to) и запрет (mustn\'t). После модального глагола всегда стоит начальная форма.',
  },
  can_could: {
    name: 'can / could',
    match: /\bcan\b|\bcould\b|\bcannot\b|can't/i,
    formula: 'can / could + V1 | Can you …? | Could you …, please?',
    signal: 'ability, permission, polite request, possibility',
    en: '"Can" expresses ability, permission and present possibility ("DKA can become life-threatening"); "could" is more tentative or polite ("Could you describe the pain?") and refers to past ability.',
    uz: "\"Can\" qobiliyat, ruxsat va hozirgi ehtimollikni bildiradi (\"DKA can become life-threatening\"); \"could\" yumshoqroq, muloyimroq (\"Could you describe the pain?\") va o'tmishdagi qobiliyatni ifodalaydi.",
    ru: '«Can» выражает способность, разрешение и возможность в настоящем («DKA can become life-threatening»); «could» — более мягкий, вежливый вариант («Could you describe the pain?») и способность в прошлом.',
  },
  may_might: {
    name: 'may / might',
    match: /\bmay\b|\bmight\b/i,
    formula: 'may / might + V1 | may / might + have + V3 (past possibility)',
    signal: 'possibly, perhaps, it is possible that',
    en: '"May" and "might" express possibility and cautious clinical judgement: "It may be an infection", "You might need to stay in hospital". "May" also gives polite permission. "Might have + V3" refers to a possible past event.',
    uz: "\"May\" va \"might\" ehtimollik va ehtiyotkor klinik xulosani bildiradi: \"It may be an infection\", \"You might need to stay in hospital\". \"May\" muloyim ruxsat ham beradi. \"Might have + V3\" — o'tmishdagi ehtimol.",
    ru: '«May» и «might» выражают возможность и осторожное клиническое суждение: «It may be an infection», «You might need to stay in hospital». «May» также даёт вежливое разрешение. «Might have + V3» — возможное событие в прошлом.',
  },
  must_have_to: {
    name: 'must / have to',
    match: /\bmust\b|have to|has to|mustn't|don't have to/i,
    formula: 'must + V1 | have to / has to + V1 | mustn\'t + V1 (prohibition) | don\'t have to + V1 (not necessary)',
    signal: 'necessity, obligation, prohibition',
    en: '"Must" expresses strong necessity from the speaker ("You must take the full course of antibiotics"); "have to" — an external rule or requirement. "Mustn\'t" means it is forbidden, while "don\'t have to" means it is not necessary.',
    uz: "\"Must\" so'zlovchining qat'iy talabini bildiradi (\"You must take the full course of antibiotics\"); \"have to\" — tashqi qoida yoki talab. \"Mustn't\" — taqiqlangan, \"don't have to\" esa — shart emas.",
    ru: '«Must» выражает строгую необходимость со стороны говорящего («You must take the full course of antibiotics»); «have to» — внешнее правило или требование. «Mustn\'t» — запрещено, «don\'t have to» — не обязательно.',
  },
  should: {
    name: 'should / ought to',
    match: /\bshould\b|ought to|shouldn't/i,
    formula: 'should / ought to + V1 | shouldn\'t + V1',
    signal: 'advice, recommendation',
    en: '"Should" and "ought to" give advice and recommendations — the most common way to tell a patient what to do: "You should drink plenty of fluids", "You shouldn\'t stop your insulin without medical advice".',
    uz: "\"Should\" va \"ought to\" maslahat va tavsiya beradi — bemorga nima qilish kerakligini aytishning eng keng tarqalgan usuli: \"You should drink plenty of fluids\", \"You shouldn't stop your insulin without medical advice\".",
    ru: '«Should» и «ought to» выражают совет и рекомендацию — самый частый способ сказать пациенту, что делать: «You should drink plenty of fluids», «You shouldn\'t stop your insulin without medical advice».',
  },
  imperative: {
    name: 'Imperatives',
    match: /imperative|buyruq|повелительн/i,
    formula: 'V1 … ! | Do not (Don\'t) + V1 | Please + V1',
    signal: 'please, do not, never, always',
    en: 'Imperatives give direct instructions and emergency commands: "Take a deep breath", "Do not eat or drink anything", "Call an ambulance immediately". "Please" or "could you" softens them for patients.',
    uz: "Buyruq gaplar to'g'ridan-to'g'ri ko'rsatma va shoshilinch buyruqlar uchun ishlatiladi: \"Take a deep breath\", \"Do not eat or drink anything\", \"Call an ambulance immediately\". Bemorga nisbatan \"please\" yoki \"could you\" bilan yumshatiladi.",
    ru: 'Повелительное наклонение даёт прямые инструкции и команды в неотложной ситуации: «Take a deep breath», «Do not eat or drink anything», «Call an ambulance immediately». Для пациента смягчается словами «please» или «could you».',
  },
  reported_speech: {
    name: 'Reported Speech',
    match: /reported speech|indirect speech|o'zlashtirma|bilvosita nutq|косвенн/i,
    formula: 'said (that) + clause with tense shifted back | told + object + (that) … | asked + if / wh-word …',
    signal: 'said, told, asked, explained, advised, backshift',
    en: 'Reported Speech relays what someone said without quoting: "My friend said that I was having an allergic reaction". Tenses usually shift back (is → was, has → had, will → would); questions use "if" or a wh-word with statement word order.',
    uz: "O'zlashtirma gap birovning gapini iqtibossiz yetkazadi: \"My friend said that I was having an allergic reaction\". Zamon odatda orqaga siljiydi (is → was, has → had, will → would); savollar \"if\" yoki so'roq so'zi bilan, darak gap tartibida beriladi.",
    ru: 'Косвенная речь передаёт чужие слова без цитирования: «My friend said that I was having an allergic reaction». Времена обычно сдвигаются назад (is → was, has → had, will → would); вопросы передаются через «if» или вопросительное слово с прямым порядком слов.',
  },
  relative_clauses: {
    name: 'Relative Clauses',
    match: /relative clause|relative pronoun|nisbiy|определительн|\bwho\b.*\bwhich\b|defining|non-defining/i,
    formula: 'noun + who / which / that / whose / where + clause',
    signal: 'who (people), which (things), that, whose, where',
    en: 'Relative clauses add information about a noun: "the patient who collapsed at work", "a test which measures kidney function". Defining clauses have no commas and identify the noun; non-defining clauses add extra information between commas.',
    uz: "Nisbiy ergash gaplar otga qo'shimcha ma'lumot beradi: \"the patient who collapsed at work\", \"a test which measures kidney function\". Aniqlovchi (defining) gaplar vergulsiz yoziladi va otni aniqlaydi; qo'shimcha (non-defining) gaplar vergullar orasida keladi.",
    ru: 'Определительные придаточные добавляют информацию о существительном: «the patient who collapsed at work», «a test which measures kidney function». Ограничительные (defining) пишутся без запятых и уточняют существительное; распространительные (non-defining) выделяются запятыми.',
  },
  participles: {
    name: 'Participles & Reduced Relative Clauses',
    match: /participle|reduced relative|sifatdosh|причасти/i,
    formula: 'V-ing + noun (active) | V3 + noun (passive) | noun + V-ing / V3 phrase',
    signal: '-ing, -ed, taken, lying, spreading',
    en: 'Present participles (-ing) describe an active process ("a spreading infection", "the patient lying in bed"); past participles (V3) describe a state or result ("an infected wound", "samples taken immediately"). They shorten relative clauses.',
    uz: "Hozirgi zamon sifatdoshi (-ing) faol jarayonni (\"a spreading infection\", \"the patient lying in bed\"), o'tgan zamon sifatdoshi (V3) holat yoki natijani (\"an infected wound\", \"samples taken immediately\") bildiradi. Ular nisbiy ergash gaplarni qisqartiradi.",
    ru: 'Причастие настоящего времени (-ing) описывает активный процесс («a spreading infection», «the patient lying in bed»); причастие прошедшего времени (V3) — состояние или результат («an infected wound», «samples taken immediately»). Они сокращают придаточные предложения.',
  },
  gerund_infinitive: {
    name: 'Gerund & Infinitive',
    match: /gerund|infinitive|to \+ v1|v-ing shakl|герунди|инфинитив/i,
    formula: 'verb + V-ing (avoid, stop, keep, recommend) | verb + to + V1 (need, want, decide, advise sb to)',
    signal: 'avoid -ing, need to, in order to, before -ing',
    en: 'Gerunds (V-ing) act as nouns and follow verbs like avoid, stop, keep, recommend and prepositions ("Avoid eating before the test"). Infinitives (to + V1) follow need, want, decide, advise someone and express purpose ("We need to run some tests", "in order to rule out appendicitis").',
    uz: "Gerund (V-ing) ot vazifasida keladi va avoid, stop, keep, recommend fe'llari hamda predloglardan keyin ishlatiladi (\"Avoid eating before the test\"). Infinitiv (to + V1) need, want, decide, advise someone dan keyin keladi va maqsadni bildiradi (\"We need to run some tests\", \"in order to rule out appendicitis\").",
    ru: 'Герундий (V-ing) выступает как существительное после глаголов avoid, stop, keep, recommend и предлогов («Avoid eating before the test»). Инфинитив (to + V1) стоит после need, want, decide, advise someone и выражает цель («We need to run some tests», «in order to rule out appendicitis»).',
  },
  comparatives: {
    name: 'Comparatives & Superlatives',
    match: /comparative|superlative|qiyosiy|orttirma|сравнительн|превосходн/i,
    formula: 'adj + -er than / more + adj + than | the + adj-est / the most + adj | good → better → the best',
    signal: 'than, the most, much / slightly + comparative, as … as',
    en: 'Comparatives compare two things ("The pain is worse than yesterday", "more severe"); superlatives pick out one from a group ("the most important sign"). Short adjectives take -er/-est, longer ones use more/most; good, bad and far are irregular.',
    uz: "Qiyosiy daraja ikki narsani solishtiradi (\"The pain is worse than yesterday\", \"more severe\"); orttirma daraja guruhdan bittasini ajratadi (\"the most important sign\"). Qisqa sifatlar -er/-est, uzunlari more/most oladi; good, bad, far — istisno.",
    ru: 'Сравнительная степень сравнивает два объекта («The pain is worse than yesterday», «more severe»); превосходная выделяет один из группы («the most important sign»). Короткие прилагательные получают -er/-est, длинные — more/most; good, bad, far — исключения.',
  },
  articles: {
    name: 'Articles & Determiners',
    match: /article|determiner|artikl|аниqlovchi|артикл|a\/an|each\/every|this\/that/i,
    formula: 'a / an + singular countable (first mention) | the + specific / known noun | no article + general plural / uncountable',
    signal: 'a, an, the, this, that, these, those, each, every',
    en: '"A/an" introduces one non-specific countable noun ("a rash", "an infection"); "the" refers to something specific or already mentioned ("the rash on his arm"). No article is used for general plurals and uncountable nouns ("children need fluids"). This/that, these/those and each/every point to particular items.',
    uz: "\"A/an\" birinchi marta tilga olingan sanaladigan otni bildiradi (\"a rash\", \"an infection\"); \"the\" aniq yoki avval aytilgan narsaga ishora qiladi (\"the rash on his arm\"). Umumiy ko'plik va sanalmaydigan otlar artiklsiz (\"children need fluids\"). This/that, these/those, each/every aniq narsalarni ko'rsatadi.",
    ru: '«A/an» вводит одно неопределённое исчисляемое существительное («a rash», «an infection»); «the» указывает на конкретное или уже упомянутое («the rash on his arm»). Без артикля — обобщённое множественное число и неисчисляемые («children need fluids»). This/that, these/those, each/every указывают на конкретные предметы.',
  },
  adverbs: {
    name: 'Adverbs',
    match: /adverb|ravish|наречи|-ly\b/i,
    formula: 'adjective + -ly (rapidly, gradually, carefully) | verb + adverb | adverb + adjective',
    signal: 'rapidly, gradually, carefully, slightly, significantly, increasingly',
    en: 'Adverbs describe how, when or to what degree something happens: "Her breathing became worse rapidly", "The condition is gradually improving". Adverbs of degree (slightly, significantly, increasingly) make clinical descriptions precise.',
    uz: "Ravishlar harakat qanday, qachon va qay darajada bo'lishini bildiradi: \"Her breathing became worse rapidly\", \"The condition is gradually improving\". Daraja ravishlari (slightly, significantly, increasingly) klinik tavsifni aniqlashtiradi.",
    ru: 'Наречия описывают, как, когда и в какой степени происходит действие: «Her breathing became worse rapidly», «The condition is gradually improving». Наречия степени (slightly, significantly, increasingly) делают клиническое описание точным.',
  },
  connectors: {
    name: 'Cause, Contrast & Time Connectors',
    match: /adverbial clause|connector|linking|cause (and|&) effect|because|although|therefore|due to|as a result|bog'lovchi|союз/i,
    formula: 'because / since / as + clause | due to / because of + noun | although / while + clause | therefore / as a result + clause',
    signal: 'because, due to, therefore, as a result, although, while, so that',
    en: 'Connectors link clinical facts logically: cause (because, since, due to), result (therefore, as a result, so), contrast (although, however, while) and time (when, while, as soon as). They turn short statements into clear clinical explanations.',
    uz: "Bog'lovchilar klinik faktlarni mantiqan bog'laydi: sabab (because, since, due to), natija (therefore, as a result, so), qarama-qarshilik (although, however, while) va vaqt (when, while, as soon as). Ular qisqa gaplarni aniq klinik tushuntirishga aylantiradi.",
    ru: 'Связующие слова логически соединяют клинические факты: причина (because, since, due to), следствие (therefore, as a result, so), противопоставление (although, however, while) и время (when, while, as soon as). Они превращают короткие фразы в ясное клиническое объяснение.',
  },
  questions: {
    name: 'Question Forms',
    match: /question form|yes\/no question|wh-question|clinical question|so'roq|savol tuzish|вопрос/i,
    formula: 'Auxiliary (do/does/did/have/is/are/can) + subject + V? | Wh-word + auxiliary + subject + V?',
    signal: 'what, when, where, how long, how often, do you, have you',
    en: 'Yes/No questions start with an auxiliary ("Do you have any allergies?", "Have you had a fever?"); Wh-questions add a question word ("How long have you had the pain?", "Where exactly does it hurt?"). Open questions gather the story, closed questions confirm details.',
    uz: "Yes/No savollar yordamchi fe'l bilan boshlanadi (\"Do you have any allergies?\", \"Have you had a fever?\"); Wh-savollar so'roq so'zi bilan (\"How long have you had the pain?\", \"Where exactly does it hurt?\"). Ochiq savollar hikoyani, yopiq savollar aniq detallarni yig'adi.",
    ru: 'Общие вопросы начинаются со вспомогательного глагола («Do you have any allergies?», «Have you had a fever?»); специальные — с вопросительного слова («How long have you had the pain?», «Where exactly does it hurt?»). Открытые вопросы собирают историю, закрытые — уточняют детали.',
  },
  indirect_questions: {
    name: 'Indirect / Polite Questions',
    match: /indirect question|polite question|embedded question|muloyim savol|косвенн\w* вопрос|could you tell me/i,
    formula: 'Could you tell me + wh-word / if + subject + verb (statement order)? | I\'d like to know …',
    signal: 'Could you tell me…, Do you know…, I wonder…',
    en: 'Indirect questions are more polite and typical of a consultation: "Could you tell me when the pain started?" (not "when did the pain start"). After the introductory phrase the word order is that of a statement, and yes/no questions use "if/whether".',
    uz: "Bilvosita savollar muloyimroq va konsultatsiya uchun odatiy: \"Could you tell me when the pain started?\" (\"when did the pain start\" emas). Kirish iborasidan keyin so'z tartibi darak gapdagidek bo'ladi; yes/no savollarda \"if/whether\" ishlatiladi.",
    ru: 'Косвенные вопросы вежливее и типичны для консультации: «Could you tell me when the pain started?» (а не «when did the pain start»). После вводной фразы сохраняется прямой порядок слов; общие вопросы вводятся через «if/whether».',
  },
  quantifiers: {
    name: 'Countable & Uncountable Nouns, Quantifiers',
    match: /countable|uncountable|quantifier|sanaladigan|sanalmaydigan|исчисляем|количествен|much\/many|some\/any/i,
    formula: 'many / a few / several + countable plural | much / a little + uncountable | some / any / a lot of + both',
    signal: 'some, any, much, many, a lot of, a little, a few, several',
    en: 'Countable nouns can be counted (symptoms, tablets, episodes) and take many/a few; uncountable nouns (pain, blood, fluid, information) take much/a little and have no plural. "Some" is used in statements and offers, "any" in questions and negatives: "Do you have any pain?"',
    uz: "Sanaladigan otlar sanaladi (symptoms, tablets, episodes) va many/a few oladi; sanalmaydigan otlar (pain, blood, fluid, information) much/a little oladi va ko'plikda kelmaydi. \"Some\" darak gap va taklifda, \"any\" savol va inkorda ishlatiladi: \"Do you have any pain?\"",
    ru: 'Исчисляемые существительные можно посчитать (symptoms, tablets, episodes) — с ними many/a few; неисчисляемые (pain, blood, fluid, information) — much/a little, без множественного числа. «Some» — в утверждениях и предложениях, «any» — в вопросах и отрицаниях: «Do you have any pain?»',
  },
  time_expressions: {
    name: 'Time Expressions (since / for / ago)',
    match: /time expression|since|\bfor\b.*\bago\b|vaqt ko'rsatkich|временн\w* выражен/i,
    formula: 'since + starting point (since yesterday) | for + period (for three days) | period + ago (two hours ago)',
    signal: 'since, for, ago, at about, over the last, until',
    en: '"Since" gives the starting point ("since yesterday"), "for" the length of time ("for three days") and "ago" counts back from now ("two hours ago"). Exact times ("at about 7:15 this morning") are essential in time-critical conditions such as stroke.',
    uz: "\"Since\" boshlanish nuqtasini (\"since yesterday\"), \"for\" davomiylikni (\"for three days\"), \"ago\" hozirdan orqaga sanashni (\"two hours ago\") bildiradi. Aniq vaqt (\"at about 7:15 this morning\") insult kabi vaqt-kritik holatlarda juda muhim.",
    ru: '«Since» указывает точку начала («since yesterday»), «for» — продолжительность («for three days»), «ago» — отсчёт назад от настоящего («two hours ago»). Точное время («at about 7:15 this morning») критично при инсульте и других неотложных состояниях.',
  },
  would_rather: {
    name: 'would rather / would prefer',
    match: /would rather|would prefer|prefer/i,
    formula: 'would rather + V1 | would prefer + to + V1 / noun',
    signal: 'preference',
    en: '"Would rather + V1" and "would prefer to + V1" express preference politely: "I would rather save the tooth than extract it", "Would you prefer a crown or an implant?"',
    uz: "\"Would rather + V1\" va \"would prefer to + V1\" afzallikni muloyim ifodalaydi: \"I would rather save the tooth than extract it\", \"Would you prefer a crown or an implant?\"",
    ru: '«Would rather + V1» и «would prefer to + V1» вежливо выражают предпочтение: «I would rather save the tooth than extract it», «Would you prefer a crown or an implant?»',
  },
  common_mistakes: {
    name: 'Common Mistakes',
    match: /common mistakes|typical mistakes|tipik xato|типичные ошибки/i,
    formula: '',
    signal: '',
    en: 'The most frequent errors students make with this module\'s grammar, each with the corrected clinical sentence.',
    uz: "Ushbu modul grammatikasida talabalar eng ko'p yo'l qo'yadigan xatolar va ularning to'g'ri klinik varianti.",
    ru: 'Самые частые ошибки студентов в грамматике этого модуля с исправленным клиническим вариантом.',
  },
};

const ORDER = Object.keys(KB);

/** Return KB keys whose pattern matches the text, in order of first occurrence. */
function detectTopics(text, max = 3) {
  const t = String(text || '');
  const hits = [];
  for (const key of ORDER) {
    const m = KB[key].match.exec(t);
    if (m) hits.push({ key, idx: m.index });
  }
  // specific tenses beat generic "modals" / "questions" when both match
  const generic = new Set(['modals', 'questions']);
  const specific = hits.filter(h => !generic.has(h.key));
  const chosen = (specific.length ? specific : hits).sort((a, b) => a.idx - b.idx).slice(0, max).map(h => h.key);
  return chosen;
}

module.exports = { KB, detectTopics };
